project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "CHA Stats in R"
  description: "Lecture notes for statistical modelling in R"

  # site-url:
  # repo-url:
  # repo-actions: [edit, issue]

  page-footer:
    # right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Sungkyun Cho"
    # background: 

  sidebar:
    # background: "#F6F6FF"
    # logo: 
    pinned: true
    align: center
    style: "docked"
    search: true
    # collapse-level: 1
    
    contents:
      - href: index.qmd
      - section: R tutorial
        contents:
          - href: contents/setup.ipynb
            text: Setup
          - href: contents/baser.ipynb
          - href: contents/tidyverse.ipynb
          - href: contents/visualize.ipynb
          # - href: contents/transform.ipynb
          # - section: contents/pandas.ipynb
          #   contents: 
          #   - href: contents/inspection.ipynb
          # - href: contents/vis.ipynb
          #   text: Data visualization
      - text: ---
      - section: Statistics
        contents:
          - href: contents/overview.ipynb 

format:
  html:
        toc: true
        toc-depth: 4
        toc-location: right
        code-fold: false
        code-overflow: scroll
        code-summary: "Show the code"
        theme: [sandstone, theme-light.scss]
        fontsize: 0.95em
        linestretch: 1.7
        code-copy: true
        highlight-style: Ayu-light
        link-external-newwindow: true
        # css: styles.css



