<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sungkyun Cho">
<meta name="dcterms.date" content="2023-02-17">

<title>CHA Stats in R - Multiple Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../contents/case1.html" rel="next">
<link href="../contents/regression1.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="../site_libs/plotly-binding-4.10.2/plotly.js"></script>
<script src="../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title">Multiple Regression</h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">CHA Stats in R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/notice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notice</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">R tutorial</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/baser.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Base R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Import</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cleaning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/visualize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualize</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/regression1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../contents/regression2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/case1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Case Study 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/case2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Case Study 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/case3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Case Study 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/case4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Salary</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Categorical IVs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inference</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Communicate</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://docs.google.com/document/d/1OQ1D7d4MxEfMZmo_FLj29rGWqvWADKmGc_QD9g5h_ho/edit?usp=sharing" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ask</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#multiple-linearregression-models" id="toc-multiple-linearregression-models" class="nav-link active" data-scroll-target="#multiple-linearregression-models">Multiple linear/regression models</a>
  <ul>
  <li><a href="#measures-of-association" id="toc-measures-of-association" class="nav-link" data-scroll-target="#measures-of-association">Measures of Association</a>
  <ul class="collapse">
  <li><a href="#회귀계수의-상대적-중요성" id="toc-회귀계수의-상대적-중요성" class="nav-link" data-scroll-target="#회귀계수의-상대적-중요성">회귀계수의 상대적 중요성</a>
  <ul class="collapse">
  <li><a href="#표준화-회귀계수-beta" id="toc-표준화-회귀계수-beta" class="nav-link" data-scroll-target="#표준화-회귀계수-beta">표준화 회귀계수 (<span class="math inline">\(\beta\)</span>)</a></li>
  </ul></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison">Model Comparison</a></li>
  </ul></li>
  <li><a href="#patterns-of-association" id="toc-patterns-of-association" class="nav-link" data-scroll-target="#patterns-of-association">Patterns of Association</a>
  <ul class="collapse">
  <li><a href="#direct-and-indirect-effects" id="toc-direct-and-indirect-effects" class="nav-link" data-scroll-target="#direct-and-indirect-effects">Direct and Indirect Effects</a></li>
  <li><a href="#spurious-relationships" id="toc-spurious-relationships" class="nav-link" data-scroll-target="#spurious-relationships">Spurious Relationships</a></li>
  <li><a href="#causal-relations" id="toc-causal-relations" class="nav-link" data-scroll-target="#causal-relations">Causal Relations</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#case-studies" id="toc-case-studies" class="nav-link" data-scroll-target="#case-studies">Case studies</a></li>
  <li><a href="#path-analysis-latent-variables" id="toc-path-analysis-latent-variables" class="nav-link" data-scroll-target="#path-analysis-latent-variables">Path Analysis &amp; Latent Variables</a>
  <ul>
  <li><a href="#latent-variable-model-잠재-변수-모형" id="toc-latent-variable-model-잠재-변수-모형" class="nav-link" data-scroll-target="#latent-variable-model-잠재-변수-모형">Latent variable model (잠재 변수 모형)</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul>
  <li><a href="#a.-mireault-1990" id="toc-a.-mireault-1990" class="nav-link" data-scroll-target="#a.-mireault-1990">A. Mireault (1990)</a></li>
  <li><a href="#b.-malcarne-compas-epping-and-howell-1995" id="toc-b.-malcarne-compas-epping-and-howell-1995" class="nav-link" data-scroll-target="#b.-malcarne-compas-epping-and-howell-1995">B. Malcarne, Compas, Epping, and Howell (1995)</a></li>
  <li><a href="#c.-guber-1999" id="toc-c.-guber-1999" class="nav-link" data-scroll-target="#c.-guber-1999">C. Guber (1999)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Multiple Regression</h1>
<p class="subtitle lead">Applied Multiple Regression/Correlation Analysis for the Behavioral Sciences by Jacob Cohen, Patricia Cohen, Stephen G. West, Leona S. Aiken</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sungkyun Cho </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 17, 2023</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="multiple-linearregression-models" class="level1">
<h1>Multiple linear/regression models</h1>
<ul>
<li>독립/예측 변수가 2개 이상인 경우</li>
<li>예측변수들 각각의 <strong>고유한 효과</strong>(effect)를 추정(estimate)</li>
<li>이는 다른 변수들의 영향이 제거된 해당 변수의 효과는 어떠한가를 의미</li>
</ul>
<p>앞서 논의된 내용은 두 변수 사이의 관계를 다룸으로써 비교적 단순한 추론 및 두 변수 간에 모종의 관계의 유무(영가설) 정도를 살펴보았음.</p>
<p>3개 이상의 변수 간의 관계에 대해서는 기하급수적으로 복잡한 관계가 나타남으로 인해, 연구자는 영향을 주고 받는 변수들 간의 <strong>인과 관계</strong>에 대해 충분한 이론적 근거를 갖고, 분석의 목적을 분명히 할 필요가 있음. (탐색적 분석이나 단순한 예측을 위한 것이 아니라면)</p>
<p>인과분석은 유전학자였던 Sewell Wright(1921)가 유전적 효과와 비유전적 효과를 분리하려는 노력하에 개발했던 경로분석 다이어그램(path analytic diagram)에 그 뿌리를 두고 있으며, 후에 구조모형(structural model)으로 불리어 이어져 왔으며, causal analysis라는 분야에서 완성되어가고 있음.</p>
<p>기본적인 인과관계의 프레임워크에서, X가 Y의 원인이기 위해서 다음 4가지 조건을 만족해야 함.</p>
<ul>
<li>X는 시간적으로 Y에 선행</li>
<li>인과적 효과를 만들어내는 기제(mechanism)를 상정할 수 있음</li>
<li>X가 변하면 Y도 변화가 발생함 (association or correlation)
<ul>
<li>X를 변화시키면 Y가 변한다는 것은 뜻은 아님.
<ul>
<li>성별처럼 변화시킬 수 없는 요인도 있음</li>
<li>X를 어떻게 manupulate 하느냐에 따라 정상적 기제가 변형되어 다른 효과가 나타날 수 있음.
<ul>
<li>임금을 갑자기 2배 올리면?</li>
<li>임금을 줄이면?</li>
</ul></li>
</ul></li>
</ul></li>
<li>다른 요인들 (confounding)을 제거한 후에도 X의 효과가 나타나야 함.
<ul>
<li>임금은 연령이 높을수록 높아지는데 삶의 만족도는 늙음으로부터 오는 정신적 여유에서 발생한 것이라면?</li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p>인과관계는 통계적 분석에 의해 증명될 수 있는 것이 아니며,<br>
<strong>관찰된 데이터와 상정한 모형이 어느 정도 일치한다</strong>라고 말할 수 있는 정도에서 결론지을 수 있으며,<br>
그 모형이 맞다면, 그 효과는 어떠하다고 실증적(empirically)으로 보이는 것임.<br>
모형의 가치는 그 구조적 논리에 크게 좌우됨.</p>
</blockquote>
<p>앞서 다뤘던 교수의 연봉에 연차와 성과물이 영향을 미친다는 인과모형을 세우면,</p>
<ul>
<li>연차와 성과물 간에 인과관계는 상정하지 않았음.</li>
<li>적어도 연봉이 성과물이나 연차에 영향을 주지는 않는다고 상정했음.</li>
</ul>
<p><img src="images/diagram2.png" class="img-fluid"></p>
<p>교수의 연봉(<code>salary</code>)이 학위를 받은 후 지난 시간(<code>time</code> since Ph.D.)과 출판물의 수(<code>pubs</code>)에 의해 어떻게 영향을 받는가?</p>
<ul>
<li>같은 연차의 교수들 간에 논문 수에 따라 연봉은 얼마나 차이가 나는가?</li>
<li>동일한 개수의 논문을 발표한 교수들 간에 연차에 따라 연봉은 얼마나 차이가 나는가?</li>
</ul>
<p>앞서 연봉에 대한 예측모형을 다음과 같이 얻었는데,</p>
<ul>
<li>Model 1: <span class="math inline">\(\widehat{salary} = \$1,224\:time + \$43,659\)</span></li>
<li>Model 2 : <span class="math inline">\(\widehat{salary} = \$336\:pubs + \$46,357\)</span></li>
</ul>
<p>다음과 같이 연차가 늘면 논문의 수도 따라서 늘어나는 경향이 있기 때문에, 연차 또는 논문 수의 고유한 효과를 추정하기 어려움.</p>
<ul>
<li><span class="math inline">\(\widehat{pubs} = 1.98\:time + 4.73\)</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>acad0 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/c0301dt.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> time, <span class="at">data =</span> acad0)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> pubs, <span class="at">data =</span> acad0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>두 개의 예측변수를 모두 포함한 모형</strong></p>
<p>Model 3: <span class="math inline">\(\widehat{Y} = a_1 X_1 + a_2 X_2 + a_0 ~ (z=2x-y+1)\)</span></p>
<p><span class="math inline">\(\widehat{salary} = \$983\:time + \$122\:pubs + \$43,082\)</span></p>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> time <span class="sc">+</span> pubs, <span class="at">data =</span> acad0)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(mod3) <span class="sc">|&gt;</span> <span class="fu">print</span>()  <span class="co"># library(jtools)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel" data-layout-ncol="1">
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<pre><code>MODEL INFO:
Observations: 15
Dependent Variable: salary
Type: OLS linear regression 

MODEL FIT:
F(2,12) = 6.78, p = 0.01
R² = 0.53
Adj. R² = 0.45 

Standard errors: OLS
------------------------------------------------------
                        Est.      S.E.   t val.      p
----------------- ---------- --------- -------- ------
(Intercept)         43082.39   3099.49    13.90   0.00
time                  982.87    452.06     2.17   0.05
pubs                  121.80    149.70     0.81   0.43
------------------------------------------------------</code></pre>
</div>
</div>
</div>
<p>The regression plane: x값이 고정될 때, 혹은 y값이 고정될 때, <strong>동일한 기울기</strong>의 직선으로 나타남.<br>
<img src="images/regression_plane.png" class="img-fluid" width="400"></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
3d plot
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-71948d22702355bf63a0" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-71948d22702355bf63a0">{"x":{"visdat":{"4251463156cf":["function () ","plotlyVisDat"]},"cur_data":"4251463156cf","attrs":{"4251463156cf":{"x":{},"y":{},"z":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d","mode":"markers","marker":{"color":[51876,54511,53425,61863,52926,47034,66432,61100,41934,47454,49832,47047,39115,59677,61458],"colorscale":["#FFE1A1","#FF4304"],"size":6},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"pubs"},"yaxis":{"title":"time"},"zaxis":{"title":"salary"}},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[18,3,2,17,11,6,38,48,9,22,30,21,10,27,37],"y":[3,6,3,8,9,6,16,10,2,5,5,6,7,11,18],"z":[51876,54511,53425,61863,52926,47034,66432,61100,41934,47454,49832,47047,39115,59677,61458],"type":"scatter3d","mode":"markers","marker":{"color":[51876,54511,53425,61863,52926,47034,66432,61100,41934,47454,49832,47047,39115,59677,61458],"colorscale":["#FFE1A1","#FF4304"],"size":6,"line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div>
</div>
</div>
<ul>
<li>교수들의 연차와 그들이 쓴 논문 수는 깊이 연관되어 있으며 (<em>r</em> = 0.66), 두 변수의 redunancy가 각 변수들의 효과를 변화시킴.</li>
<li>두 예측 변수의 산술적 합으로 연봉을 예측하므로 각 예측변수의 효과는 수정될 수 밖에 없음.</li>
<li>수학적으로 보면, 각 예측변수의 기울기는 다른 예측변수의 값에 상관없이 일정하므로, 다른 예측변수들을 (임의의 값에) <strong>고정시키는 효과</strong>를 가짐</li>
<li>즉, 다른 변수와는 독립적인, <strong>고유한 효과</strong>를 추정하게 됨</li>
</ul>
<p>세 모형을 비교하면,</p>
<p>Model 1: <span class="math inline">\(\widehat{salary} = \$1,224\:time + \$43,659\)</span><br>
Model 2 : <span class="math inline">\(\widehat{salary} = \$336\:pubs + \$46,357\)</span><br>
Model 3: <span class="math inline">\(\widehat{salary} = \$983\:time + \$122\:pubs + \$43,082\)</span></p>
<ul>
<li>연차(<code>time</code>)의 효과는 $1,224에서 $984로 낮아졌고,</li>
<li>논문수(<code>pubs</code>)의 효과는 $336에서 $122로 낮아졌음.</li>
</ul>
<p>각 회귀계수를 partial regression coefficient (부분 회귀 계수) 라고 부름.</p>
<p><strong>부분 회귀 계수의 첫번째 해석</strong>:</p>
<ul>
<li>만약 논문 수가 일정할 때, 예를 들어 10편의 논문을 쓴 경우만 봤을 때, 연차가 1년 늘 때마다 연봉은 $984 증가함; 평면의 선형모형을 가정했기에 이 관계는 논문 수에 상관없음.<br>
</li>
<li>연차가 일정할 때, 예를 들어 연차가 12년차인 경우만 봤을 때, 논문이 1편 늘 때마다 연봉은 $336 증가함; 평면의 선형모형을 가정했기에 이 관계는 연차에 상관없음.</li>
</ul>
<p>이는 다른 <strong>변수를 고려 (통제, controlling for) 했을 때 혹은 다른 변수의 효과를 제거 (partial out) 했을 때</strong>, 각 변수의 <strong>고유한 효과</strong>를 의미함; <strong><em>holding constant, controlling for, partialing out, adjusted for, residualizing</em></strong></p>
<p>뒤집어 말하면, 연차만 고려했을때 연차가 1년 늘면 $1,224 연봉이 증가하는 효과는 연차가 늘 때 함께 늘어나는 논문 수의 효과가 함께 섞여 나온 효과라고 말할 수 있음.</p>
<p>이는 인과관계에 있는 변수들의 진정한 효과를 찾는 것이 얼마나 어려운지를 보여줌</p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="images/salary_model1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" width="410"></p>
</figure>
</div>
<blockquote class="blockquote">
<p>The partial regression coefficients, $983 and $122, are the empirical estimates, respectively, of h and g, the causal effects of our independent variables accompanying the arrows in the causal diagram (Fig. 3.1.1) (p.&nbsp;69).</p>
</blockquote>
<p><strong>부분 회귀 계수에 대한 두번째 해석</strong></p>
<ul>
<li>다른 변수들이 <strong>partial out</strong> 된 후의 효과.<br>
</li>
<li>실제로 $122는 연차로 (선형적으로) 예측되지 않는 논문수(residuals)로 [연차로 예측되지 않는] 연봉을 예측할 때의 기울기</li>
</ul>
<p>논문 수(<span class="math inline">\(X_2\)</span>)에 대한 부분 회귀 계수에 대해 자세히 들여다 보면,</p>
<p>  <img src="images/partial1.png" class="img-fluid" width="260"></p>
<p><span class="math inline">\(\widehat{Y_1}: X_1\)</span> 으로만 <span class="math inline">\(Y\)</span>를 예측했을 때의 예측치, &nbsp; <span class="math inline">\(\widehat{Y}_{12}: X_1\)</span>과 <span class="math inline">\(X_2\)</span> 로 함께 <span class="math inline">\(Y\)</span>를 예측했을 때의 예측치<br>
<span class="math inline">\(\widehat{X}_{2.1}\)</span>: <span class="math inline">\(X_1\)</span> 으로 <span class="math inline">\(X_2\)</span> 를 예측했을 때의 예측치; 연차로 예측된 논문수<br>
<span class="math inline">\(X_2 - \widehat{X}_{2.1}\)</span>: <span class="math inline">\(X_1\)</span>으로 <span class="math inline">\(X_2\)</span>를 예측했을 때의 예측하지 못한 잔차: 연차로 예측되지 않는 논문수<br>
<span class="math inline">\(Y-\widehat{Y}_1\)</span>: <span class="math inline">\(X_1\)</span>으로 예측되지 않는 <span class="math inline">\(Y\)</span> : 연차로 예측되지 않는 연봉</p>
<p>논문 수(<span class="math inline">\(X_2\)</span>)에 대한 부분 회귀 계수: [연차로 예측되지 않는 논문 수]와 [연차로 예측되지 않는 연봉] 간의 선형관계에 대한 계수</p>
<p><span class="math inline">\(\widehat{salary} = \$983\:time + \$122\:pubs + \$43,082\)</span></p>
<ul>
<li><span class="math inline">\(\widehat{salary} = \$1,224\:time + \$43,659\)</span><br>
</li>
<li><span class="math inline">\(\widehat{pubs} = 1.98\:time + 4.73\)</span></li>
</ul>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="images/partial_regression.png" class="img-fluid quarto-figure quarto-figure-left figure-img" width="810"></p>
</figure>
</div>
<p><strong>Added-variable plots</strong><br>
aka partial regression plots</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(mod3) <span class="co"># partial regression plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Marginal vs.&nbsp;Conditional Plots</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="measures-of-association" class="level2">
<h2 class="anchored" data-anchor-id="measures-of-association">Measures of Association</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="fragment">
<p><span class="math inline">\(R\)</span>: <strong>Multiple correlation coefficient</strong></p>
<ul>
<li><span class="math inline">\(Y\)</span> 와 <span class="math inline">\(\widehat Y\)</span> 의 correlation 즉, Y와 회귀모형이 예측한 값의 (선형적) 상관 관계의 정도; 회귀모형의 예측의 정확성<br>
</li>
<li>다시말하면, 예측변수들의 최적의 선형 조합과 Y의 상관 관계의 정도.</li>
</ul>
<p><span class="math inline">\(R^2\)</span>: (평면의) 선형모형에 의해 설명된 Y 변량의 비율:<br>
또는 예측변수들의 최적의 선형 조합에 의해 설명된 Y 변량의 비율.<br>
즉, <span class="math inline">\(\displaystyle\frac{V(\widehat{Y})}{V(Y)}\)</span> 또는 <span class="math inline">\(\displaystyle 1 - \frac{V(e)}{V(Y)}\)</span></p>
</div>
</div><div class="column" style="width:40%;">
<div class="fragment">
<p><img src="images/partial3.png" class="img-fluid" width="320"></p>
</div>
</div>
</div>
<p><strong>Partial Associations</strong></p>
<ul>
<li>Partial correlation <em>(pr)</em></li>
<li>Semi-partial correlation <em>(sr)</em></li>
</ul>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/partial1.png" class="img-fluid" width="260"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/partial2.png" class="img-fluid" width="340"></p>
</div>
</div>
</div>
<p><span class="math inline">\(pr^2\)</span> : “연차로 설명되지 않는 연봉”의 변량 중 “연차로 설명되지 않는 논문수”의 변량으로 설명되는 비율<br>
즉, 연차를 연봉과 논문수에서 모두 partial out 시켰을 때 남은(residualized) 연봉의 변량과 논문수의 변량의 중복 정도.</p>
<p><span class="math inline">\(sr^2\)</span> : 연봉의 변량 중 “연차로 설명되지 않는 논문수”의 변량으로 설명되는 비율<br>
즉, 연차를 논문수에서만 partial out 시켰을 때 남은(residualized) 논문수의 변량과 연봉의 변량의 중복 정도.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(mod3, <span class="at">part.corr =</span> <span class="cn">TRUE</span>, <span class="at">model.info =</span> <span class="cn">FALSE</span>, <span class="at">model.fit =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard errors: OLS
---------------------------------------------------------------------------
                        Est.      S.E.   t val.      p   partial.r   part.r
----------------- ---------- --------- -------- ------ ----------- --------
(Intercept)         43082.39   3099.49    13.90   0.00                     
time                  982.87    452.06     2.17   0.05        0.53     0.43
pubs                  121.80    149.70     0.81   0.43        0.23     0.16
---------------------------------------------------------------------------</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Correlations tables
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">partial.r</span>(acad0, <span class="fu">c</span>(<span class="st">"salary"</span>, <span class="st">"time"</span>), <span class="st">"pubs"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># partial correlations </span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#        salary time</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># salary   1.00 0.53</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># time     0.53 1.00</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">partial.r</span>(acad0, <span class="fu">c</span>(<span class="st">"salary"</span>, <span class="st">"pubs"</span>), <span class="st">"time"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># partial correlations </span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co">#        salary pubs</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># salary   1.00 0.23</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># pubs     0.23 1.00</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cor2</span>(acad0[<span class="fu">c</span>(<span class="st">"time"</span>, <span class="st">"pubs"</span>)], acad0[<span class="st">"salary"</span>])</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="co">#      salary</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co"># time   0.71</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="co"># pubs   0.59</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>Correlations with <code>salary</code></p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[50, -2, 48]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">\(r\)</span> <em>(simple)</em></th>
<th style="text-align: center;"><span class="math inline">\(pr\)</span> <em>(partial)</em></th>
<th style="text-align: center;"><span class="math inline">\(sr\)</span> <em>(semi-partial)</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">time</td>
<td style="text-align: center;">0.71</td>
<td style="text-align: center;">0.53</td>
<td style="text-align: center;">0.43</td>
</tr>
<tr class="even">
<td style="text-align: center;">pubs</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">0.23</td>
<td style="text-align: center;">0.16</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 48.0%;justify-content: center;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">\(r^2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(pr^2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(sr^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">time</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.28</td>
<td style="text-align: center;">0.18</td>
</tr>
<tr class="even">
<td style="text-align: center;">pubs</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.03</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Summarizing the results for the running example, we found <span class="math inline">\(sr^2\)</span> = .1850, <span class="math inline">\(pr^2\)</span> = .2826 and <span class="math inline">\(sr^2\)</span> = .0258, <span class="math inline">\(pr^2\)</span> = .0522. Whichever base we use, it is clear that number of publications (<span class="math inline">\(X_2\)</span>) has virtually no unique relationship to salary, that is, no relationship beyond what can be accounted for by time since doctorate (<span class="math inline">\(X_1\)</span>). On the other hand, time since doctorate (<span class="math inline">\(X_1\)</span>) is uniquely related to salary (<span class="math inline">\(sr_1\)</span>) and to salary holding publications constant (<span class="math inline">\(pr_1\)</span>) to a quite substantial degree. (p.75)</p>
</blockquote>
<section id="회귀계수의-상대적-중요성" class="level3">
<h3 class="anchored" data-anchor-id="회귀계수의-상대적-중요성">회귀계수의 상대적 중요성</h3>
<p>참고: Chapter 8. Assessing the Importance of Regressors,<br>
in <em>Regression Analysis and Linear Models by Richard B. Darlington &amp; Andrew F. Hayes</em></p>
<p>모든 상황에 적용할 수 있는 하나의 방법은 없으며,<br>
연구 내용과 측정 변수들의 특성에 따라 적절한 방법을 선택. (여전히 논쟁 중이며, 연구 중)</p>
<ul>
<li>표준화 회귀계수 (standardized regression coefficient)</li>
<li><strong>Semi-partial correlation</strong> coefficient <em>(sr)</em> **</li>
<li><strong>Semi-partial correlation</strong> squared <em>(<span class="math inline">\(sr^2\)</span>)</em> (by David C. Howell)</li>
<li>Dominance analysis</li>
</ul>
<section id="표준화-회귀계수-beta" class="level4">
<h4 class="anchored" data-anchor-id="표준화-회귀계수-beta">표준화 회귀계수 (<span class="math inline">\(\beta\)</span>)</h4>
<p>Standardized regression coefficient</p>
<ul>
<li>표준화하여 각 변수들의 단위가 1sd로 같아져 계수들 간에 비교가 용이하나</li>
<li>표준화에 (심각하게) 반대하는 의견도 있음.
<ul>
<li>현 표본의 특성을 반영하여, 샘플들마다 계수값이 크게 달라질 수 있음. (특히, 변수들간의 상관이 큰 경우)</li>
<li>표준화가 무의미한 변수들도 존재하며; ex. 성별</li>
<li>인과적 의미를 지니려면 원 단위로 표현하는 것이 더 적절함. (1sd 만큼 늘어났다는 것이 의미가 있을까?)</li>
</ul></li>
<li>Simple regression의 경우, <span class="math inline">\(\beta = r\)</span> 즉, 표준화 회귀계수는 상관계수와 같음.
<ul>
<li><span class="math inline">\(b = r\)</span>, &nbsp; (<span class="math inline">\(b=r \frac{sd_Y}{sd_X}\)</span>)</li>
<li><span class="math inline">\(b_i = \beta_i \frac{sd_Y}{sd_i}\)</span></li>
</ul></li>
</ul>
<p>R에서 표준화 계수를 구하는 방식: <code>scale()</code>, <code>summ()</code></p>
<ol type="1">
<li><code>scale()</code> 함수로 각 변수들을 직접 표준화<br>
참고: 표준화 한 후 estimate한 방식 vs.&nbsp;estimate한 후 표준화한 방식</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>acad0 <span class="ot">&lt;-</span> acad0 <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">time_std =</span> <span class="fu">scale</span>(time),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">pubs_std =</span> <span class="fu">scale</span>(pubs),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">salary_std =</span> <span class="fu">scale</span>(salary)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>또는 formula에서 직접 처리</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="fu">lm</span>(<span class="fu">scale</span>(salary) <span class="sc">~</span> <span class="fu">scale</span>(time) <span class="sc">+</span> <span class="fu">scale</span>(pubs), <span class="at">data =</span> acad0))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term        estimate std.error statistic p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept) 2.37e-16     0.191  1.24e-15  1.00  
2 scale(time) 5.70e- 1     0.262  2.17e+ 0  0.0504
3 scale(pubs) 2.13e- 1     0.262  8.14e- 1  0.432 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li><code>summ()</code> 함수의 옵션 <code>scale</code>, <code>transform.response</code>을 이용</li>
</ol>
<ul>
<li>선별적으로 표준화할 변수를 지정할 수 없어서 부적절한 경우 존재</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(mod3, <span class="at">scale =</span> <span class="cn">TRUE</span>, <span class="at">transform.response =</span> <span class="cn">TRUE</span>, <span class="at">model.info =</span> <span class="cn">FALSE</span>, <span class="at">model.fit =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard errors: OLS
-----------------------------------------------
                    Est.   S.E.   t val.      p
----------------- ------ ------ -------- ------
(Intercept)         0.00   0.19     0.00   1.00
time                0.57   0.26     2.17   0.05
pubs                0.21   0.26     0.81   0.43
-----------------------------------------------

Continuous variables are mean-centered and scaled by 1 s.d.</code></pre>
</div>
</div>
<p>mod3에서 연봉에 미치는 연차와 논문수의 상대적 중요성에 대한 지표 비교</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[50, -2, 48]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">\(\beta\)</span></th>
<th style="text-align: center;"><span class="math inline">\(sr\)</span></th>
<th style="text-align: center;"><span class="math inline">\(sr^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">time</td>
<td style="text-align: center;">0.57</td>
<td style="text-align: center;">0.43</td>
<td style="text-align: center;">0.18</td>
</tr>
<tr class="even">
<td style="text-align: center;">pubs</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">0.03</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
</div>
</div>
</section>
</section>
<section id="model-comparison" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison">Model Comparison</h3>
<ol type="1">
<li>mod1 vs.&nbsp;mod3: nested model</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> time, <span class="at">data =</span> acad0)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> time <span class="sc">+</span> pubs, <span class="at">data =</span> acad0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li>연차로 연봉의 변량을 설명한 모형에 논문 수가 예측변수로 추가되었을 때, 추가로 연봉의 변량을 얼마나 설명하는가?</li>
<li><span class="math inline">\(R^2\)</span>의 증가량을 통해 파악할 수 있음.</li>
<li><span class="math inline">\(\Delta R^2\)</span> = 0.530 - 0.505 = 0.025</li>
<li><span class="math inline">\(sr^2\)</span> 과 동일 (<em>semi-partial squared</em>)</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/sp1.png" class="img-fluid" width="320"></p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(mod1)  <span class="co"># library(broom)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.505         0.466 5763.      13.2 0.00300     1  -150.  306.  308.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.530         0.452 5839.      6.78  0.0107     2  -150.  307.  310.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p><span class="math inline">\(\Delta R^2\)</span> 가 통계적으로 유의한지, 즉 유의하지 증가했는지를 확인</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod1, mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  Res.Df        RSS    Df `Sum of Sq`      F `Pr(&gt;F)`
   &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
1     13 431731655.    NA         NA  NA       NA    
2     12 409159359.     1   22572295.  0.662    0.432</code></pre>
</div>
</div>
<p><br> 2. mod2 vs.&nbsp;mod3: nested model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> pubs, <span class="at">data =</span> acad0)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> time <span class="sc">+</span> pubs, <span class="at">data =</span> acad0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li>논문수로 연봉의 변량을 설명한 모형에 연차가 예측변수로 추가되었을 때, 추가로 연봉의 변량을 얼마나 설명하는가?</li>
<li><span class="math inline">\(R^2\)</span>의 증가량을 통해 파악할 수 있음.</li>
<li><span class="math inline">\(\Delta R^2\)</span> = 0.530 - 0.346 = 0.184</li>
<li><span class="math inline">\(sr^2\)</span> 과 동일 (<em>semi-partial squared</em>)</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/sp2.png" class="img-fluid" width="320"></p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(mod2)  <span class="co"># library(broom)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.346         0.295 6624.      6.86  0.0212     1  -152.  310.  312.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.530         0.452 5839.      6.78  0.0107     2  -150.  307.  310.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p><span class="math inline">\(\Delta R^2\)</span> 가 통계적으로 유의한지, 즉 유의하지 증가했는지를 확인</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod2, mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  Res.Df        RSS    Df `Sum of Sq`     F `Pr(&gt;F)`
   &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
1     13 570340401.    NA         NA  NA     NA     
2     12 409159359.     1  161181042.  4.73   0.0504</code></pre>
</div>
</div>
</section>
</section>
<section id="patterns-of-association" class="level2">
<h2 class="anchored" data-anchor-id="patterns-of-association">Patterns of Association</h2>
<section id="direct-and-indirect-effects" class="level3">
<h3 class="anchored" data-anchor-id="direct-and-indirect-effects">Direct and Indirect Effects</h3>
<p>만약, 다음과 같은 인과모형을 세운다면,</p>
<p><img src="images/salary_model2.png" class="img-fluid" width="450"></p>
<ul>
<li>연차가 연봉에 미치는 효과가 두 경로로 나뉘어지고,</li>
<li>연차 <span class="math inline">\(\rightarrow\)</span> 연봉: <strong>직접효과</strong> $983</li>
<li>연차 <span class="math inline">\(\rightarrow\)</span> 논문 <span class="math inline">\(\rightarrow\)</span> 연봉: <strong>간접효과</strong> 1.98 x $122 = $241.56</li>
<li>두 효과를 더하면: $983 + $241.56 = $1224.56 = 논문수를 고려하지 않았을 때 연차의 효과
<ul>
<li>즉, 연차가 1년 늘때 연봉이 $1224 증가하는 것은 연차 자체의 효과($983)와 논문의 증가에 따른 효과($241)가 합쳐져 나온 결과라고 말할 수 있음.</li>
</ul></li>
<li>이 때, 논문의 수가 연차와 연봉의 관계를 (부분) 매개한다고 표현. (mediation)</li>
</ul>
<p>만약, 연차의 효과 $1224이 논문수를 고려했을 때 줄어든($983) 수준을 훨씬 넘어 통계적으로 유의하지 않을 정도로 0에 가까워진다면, 연차의 효과는 모두 논문의 효과를 거쳐 나타나는 것이라고 말할 수 있음. 이 때, 완전 매개 (fully mediate)한다고 표현함.</p>
<p><img src="images/salary_model3.png" class="img-fluid" width="400"></p>
<p>매개효과의 통계적 분석 절차는 여러 방식이 제시되고 있으나, 일반적인 절차는 부트스랩핑(bootstraping)을 통해 추정.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>mod_med <span class="ot">&lt;-</span> <span class="fu">mediate</span>(salary <span class="sc">~</span> time <span class="sc">+</span> (pubs), <span class="at">data =</span> acad0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/mediation_salary.png" class="img-fluid" width="500"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_med)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: mediate(y = salary ~ time + (pubs), data = acad0)

Direct effect estimates (traditional regression)    (c') X + M on Y 
            salary      se     t df     Prob
Intercept 43082.39 3099.49 13.90 12 9.26e-09
time        982.87  452.06  2.17 12 5.04e-02
pubs        121.80  149.70  0.81 12 4.32e-01

R = 0.73 R2 = 0.53   F = 6.78 on 2 and 12 DF   p-value:  0.0107 

 Total effect estimates (c) (X on Y) 
            salary      se     t df     Prob
Intercept 43658.59 2978.02 14.66 13 1.83e-09
time       1224.39  336.48  3.64 13 3.00e-03

 'a'  effect estimates (X on M) 
          pubs   se    t df    Prob
Intercept 4.73 5.59 0.85 13 0.41300
time      1.98 0.63 3.14 13 0.00783

 'b'  effect estimates (M on Y controlling for X) 
     salary    se    t df  Prob
pubs  121.8 149.7 0.81 12 0.432

 'ab'  effect estimates (through all  mediators)
     salary   boot     sd   lower  upper
time 241.53 230.31 277.03 -300.24 778.08</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="spurious-relationships" class="level3">
<h3 class="anchored" data-anchor-id="spurious-relationships">Spurious Relationships</h3>
<p>사실, 위에서 다룬 데이터(N=15)로만 보자면,<br>
논문수(<code>pubs</code>)와 연봉(<code>salary</code>)의 관계는 <strong>spurious</strong>한 관계라고 잠정적으로 말할 수 있음.</p>
<ul>
<li>연차(<code>time</code>)가 “통계적으로 통제” 혹은 “partial out” 되었을 때,<br>
partial correlation <span class="math inline">\(pr\)</span> = 0.23 이며, 그 제곱 <span class="math inline">\(pr^2\)</span> = 0.05</li>
<li>뿐만 아니라, <em>not significant</em></li>
</ul>
<p>연차(<code>time</code>)를 논문수와 연봉의 <strong>common cause</strong> 라고 말하며, <strong>confounding</strong>이 되어 논문수와 연봉의 인과관계는 실제로 없을 수 있음을 암시함.</p>
<p><img src="images/salary_model4.png" class="img-fluid" width="500"></p>
<hr>
</section>
<section id="causal-relations" class="level3">
<h3 class="anchored" data-anchor-id="causal-relations">Causal Relations</h3>
<p>세 변수 간의 일반적인 인과관계의 형태에 대해서 분류해보면, (p.76, p.458)</p>
<p><img src="images/causal_rel2.png" class="img-fluid" style="width:100.0%"></p>
<p>흔히 나타나는 partial redundancy인 Model B의 예를 보면,</p>
<p><img src="images/causal_rel3.png" class="img-fluid" width="800"></p>
<p>Moderators (조절변수): interaction effects<br>
ex. 연령(X)에 따라 지구력(Y)이 감소하는 관계가 운동한 기간(Z)에 따라 변화</p>
<p><img src="images/causal_rel4.png" class="img-fluid" width="380"></p>
<hr>
</section>
</section>
</section>
<section id="case-studies" class="level1">
<h1>Case studies</h1>
<ul>
<li><strong>Leerkes and Crockenberg (1999)</strong>의 육아에 대한 효능감 연구<br>
</li>
<li><strong>Guber (1999)</strong>의 SAT 점수와 주(states)의 교육지출 사이의 관계<br>
</li>
<li><strong>National Education Longitudinal Study of 1988</strong>: 10학년 학생들의 과제와 성적과의 관계</li>
</ul>
<hr>
</section>
<section id="path-analysis-latent-variables" class="level1">
<h1>Path Analysis &amp; Latent Variables</h1>
<p>연봉에 미치는 영향에 대한 full model (p.461)<br>
<img src="images/salary_model_full.png" class="img-fluid" width="550"></p>
<ul>
<li>Exogenous and endogenous variables</li>
<li><span class="math inline">\(U_Y\)</span>: “<span class="math inline">\(e_Y\)</span> (for error variance) or <span class="math inline">\(U_Y\)</span> (for <strong>unmeasured causes</strong>), representing the miscellaneous unknown or unmeasured(”random”) causes of variables, about which our data, and perhaps our theory as well, are silent”</li>
<li><span class="math inline">\(U_Y\)</span>는 모든 측정된 변수와 독립임을 가정: 그렇지 않으면 인과를 유추하기 어려워짐. 숨은 confounder가 존재할 수 있는 가능성이 존재.</li>
</ul>
<blockquote class="blockquote">
<p>An important set of residual causes of our variables as measured in the behavioral sciences are those collectively referred to as <strong><em>measurement error</em></strong>, and including such things as day to day or moment to moment fluctuation in response probability, unclean test tubes or imperfectly standardized reagents, the impact of temporary illness or fatigue, or that miscellany of item content that is irrelevant to the main thrust of the measures included in the model. (p.&nbsp;459)</p>
</blockquote>
<p>Causal claim를 하기 위해서는 항상 주의해야 하며,<br>
회귀계수가 인과관계를 올바르게 표현하려면, 주요한 confounding이 모형에 포함되어 있어 모형을 심각히 왜곡하는 spurious한 관계들이 제거되어야 함.</p>
<ul>
<li>앞서 다룬 예제에서보면, 논문 한 편의 증가가 연봉을 평균적으로 $336 증가시킨다고 말하는 것은 연차라는 common cause가 존재하지 않을 때에 가능함.</li>
<li>실제로 연차를 모형에 포함함으로써 논문의 영향력은 $122로 줄었음.</li>
</ul>
<p>모든 spurious한 관계를 다 제거할 수 없기는 하나 중요한 confounder을 찾아 모형에 포함시키는 노력이 필요.<br>
적어도 mediator들이 빠진 것은 모형을 심각히 저해하지는 않음.</p>
<ul>
<li>예를 들어 학장과의 정치적 단결, 다른 대학으로부터의 취업 제안을 알리거나, 대학에서의 과거 및 현재 다른 활동들이 연봉에 영향을 미칠 수 있음.</li>
<li>하지만, 이는 mediator들이 될 수 있으나 confounder들은 아님.</li>
</ul>
<p>연구자가 설정한 모형이 데이터와 일치하는가에 대한 모형 적합도 (model fit)를 살펴볼 수 있는데, 다음과 같이<br>
<strong>model implied/predicted covariance</strong> 과 actual covariance (saturated model)가 얼마나 불일치하는지에 대한 다양한 지표들을 이용해 설정한 모형이 틀린 모형은 아닐 것이라고 추정할 수 있음.</p>
<p>예를 들어, 연구자가 다음 그림의 두번째 모형을 세웠다면,</p>
<p><img src="images/sem_salary.png" class="img-fluid" width="700"></p>
<p><em>회귀계수의 비교</em> (<code>salary</code> 단위: 1000)</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       salary  pubs  time
salary      0 0.122 0.983
pubs        0 0.000 1.983
time        0 0.000 0.000</code></pre>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       salary  pubs  time
salary      0 0.336 0.000
pubs        0 0.000 1.983
time        0 0.000 0.000</code></pre>
</div>
</div>
</div>
<p><em>상관계수의 비교</em></p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       salary  pubs  time
salary  1.000            
pubs    0.588 1.000      
time    0.710 0.657 1.000</code></pre>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       salary  pubs  time
salary  1.000            
pubs    0.588 1.000      
time    0.386 0.657 1.000</code></pre>
</div>
</div>
</div>
<p><em>상관계수의 차이</em><br>
actual correlation/covariance (saturated model) vs.&nbsp;<strong>model implied/predicted</strong> correlation/covariance matrix</p>
<ul>
<li>raw vs.&nbsp;standardized</li>
</ul>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       salary  pubs  time
salary  0.000            
pubs    0.000 0.000      
time    0.324 0.000 0.000</code></pre>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       salary  pubs  time
salary  0.000            
pubs    0.000 0.000      
time    1.963 0.000 0.000</code></pre>
</div>
</div>
</div>
<p>위의 covariance matrix를 이용하여 다양한 지표들이 이용해 모형의 적합도를 추정</p>
<ul>
<li>산술적 차이나 비율등의 차이로 비교 (residual covariance matrix, 잔차 행렬)
<ul>
<li>SRMR : 잔차 covariace 값들의 평균 정도를 수량화</li>
</ul></li>
<li>inferential vs.&nbsp;descriptive indices
<ul>
<li><span class="math inline">\(\chi^2\)</span> : saturated 모형과 설정한 모형이 같다는 가설을 통계적으로 검정</li>
<li>GFI, NFI 등</li>
</ul></li>
<li>alternatives: RMSEA, CFI 등</li>
</ul>
<section id="latent-variable-model-잠재-변수-모형" class="level4">
<h4 class="anchored" data-anchor-id="latent-variable-model-잠재-변수-모형">Latent variable model (잠재 변수 모형)</h4>
<p>앞서 논의한 회귀분석은 구체적으로 측정한 변수들간의 관계에 대한 것이었는데, 연구자는 원래 좀 더 추상적이고 개념적인 <strong>construct</strong>에 대해 이론적 논의를 하고자 하는 취지에서 시작한 것일 수 있음. 예를 들어, 아래 그림과 같이 (p.471)</p>
<ul>
<li>연봉은 사회의 보상체계 (reward system)의 한 단면을 본 것이고,</li>
<li>논문수는 개인의 생산성 (productivity)를</li>
<li>인용수는 개인의 역량/우수성 (eminence)를</li>
<li>연차는 개인의 연륜 (seniority)를</li>
<li>성별은 사회적 지위 (status position)라는 construct를 구성하는 요소로 볼 수 있음.</li>
</ul>
<p><img src="images/salary_latent.png" class="img-fluid" width="700"></p>
<p>연구자는 대학기관에서 보상체계에 영향을 주는 이론적 construct의 상대적 영향을 탐구할 목적으로, 구체적인 한 단면을 들여다 봄으로써 그 영향력에 대해 살펴볼 수 있었고, 궁극적으로 다른 기관들 (ex. 정부기관, 기업체 등)에서의 사회보상체계에 대해서도 비교해볼 수 있음.</p>
<p>한편, 이론적인 construct의 프레임워크에서 탐구하고자 한다면, 각 construct의 다양한 면을 모두 포함하도록 하는 것이 이상적이며, 이를 construct를 상징하는 (unobserved) latent variable (잠재 변수)로 취급하여 latent variable model (잠재 변수 모형)을 구성할 수 있음.</p>
<ul>
<li>잠재변수의 구성에 관한 <strong>measuremnt model (측정 모형)</strong> 부분과 (factor analysis)</li>
<li>잠재변수들간의 관계에 관한 <strong>structural model (구조 모형)</strong> 부분으로 구성됨.</li>
<li>장점 중의 하나는 the error-free constructs의 효과를 추정</li>
<li>두번째 장점은 an overall test of the fit of the model to the data</li>
</ul>
<p>많은 (측정) 변수들을 동시에 고려해서 잠재 변수 모형을 세우기보다는 3, 4개의 변수들로 이루어진 2, 3개의 잠재 변수들로 구성된 모형의 일부분을 하나씩 살펴보는 것이 효과적이며, 이후 변수들을 추가하거나 모형의 다른 부분을 탐색하는 것이 적절함.</p>
<p>인과모형에서 가장 중요한 것은 논리적이고 이론적인 뒷받침하에 그 타당성이 힘을 얻는 것임을 명심.<br>
예를 들어, 논문수가 인용수에 영향을 미친다고 설정한 모형과 그 반대로 설정한 모형 중 어느 모형이 더 타당한지는 데이터로 실증적으로 검증할 수 없음. (소위 equivalent models)</p>
<hr>
</section>
</section>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<p>Source: p 570, Statistical Methods for Psychology (8e) by Dave C. Howell</p>
<section id="a.-mireault-1990" class="level3">
<h3 class="anchored" data-anchor-id="a.-mireault-1990">A. Mireault (1990)</h3>
<p>Data: <a href="https://www.dropbox.com/s/3pjycx17hium0km/mireault.csv?dl=1">Mireault.csv</a></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Data Description
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Mireault (1990) collected data from 381 college students, some of whom had lost a parent by death during their childhood. She had three groups of students. Group I was composed of subjects who had lost a parent. Group 2 was composed of subjects whose parents were still alive and married to each other. Group 3 consisted of students whose parents were divorced. Mireault was interested in observing the effects of parental loss on the person’s current level of symptomatology (as measured by the Brief Symptom Inventory, Derogatis, 1983) and on the individual’s self-perceived vulnerability to future loss. In the interest of space, the data set includes only the total vulnerability measure, and not the subscales. There is also a single measure for social support. For all measures, a higher score represents more of the concept being measured. The variables, and their location in the file, are listed following the sample data. Missing data are represented by a period. The first three lines of data are shown below as an example.</p>
<p>ID 1-3 Subject identification number<br>
Group 5 1 = loss; 2 = married; 3 = divorced<br>
Gender 7 1 = male; 2 = female<br>
YearColl 9 1 = first year; 2 = sophomore; and so on<br>
College 11 1 = arts and sciences; 2 = health; 3 = engineering; 4 = business; 5 = agriculture<br>
GPA 13 4 = A; 3 = B; 2 = C; 1 = D; 0 = F<br>
LostPGen 15 Gender of lost parent<br>
AgeAtLos 17-18 Age at parent’s death<br>
SomT 20-21 Somatization T score<br>
ObsessT 23-24 Obsessive-compulsive T score<br>
SensitT 26-27 Interpersonal sensitivity T score<br>
DepressT 29-30 Depression T score<br>
AnxT 32-33 Anxiety T score<br>
HostT 35-36 Hostility T score<br>
PhobT 38-39 Phobic anxiety T score<br>
ParT 41-42 Paranoid ideation T score<br>
PsyT 44-45 Psychoticism T score<br>
GSIT 47-48 Global symptom index T score<br>
PVTotal 50-52 Perceived vulnerability total score<br>
PVLoss 54-56 Perceived vulnerability to loss<br>
SuppTotl 58-60 Social support score</p>
</div>
</div>
</div>
<p>15.26 Use the data set Mireault.dat from Mireault (1990), described in the Appendix and found on the Web site for this book, to examine the relationship between current levels of depression and other variables. A reasonable model might propose that depression (DepressT) is a function of (1) the person’s current perceived level of vulnerability to additional loss (PVLoss), (2) the person’s level of social support (SuppTotl), and (3) the age at which the person lost a parent during childhood (AgeAtLos). Use any statistical package to evaluate the model outlined here. (Because only subjects in Group 1 lost a parent to death during childhood, your analysis will be restricted to that group.)</p>
<p><img src="images/mireault1.png" class="img-fluid" width="450"></p>
<p>15.28 In Exercise 15.26 we posited a model in which depression was a function of perceived vulnerability, social support, and age at loss. An alternative, or additional, view might be that vulnerability itself is a function of social support and age at loss. (If you lost a parent when you were very young and you have little social support, then you might feel particularly vulnerable to future loss.)</p>
<p><img src="images/mireault2.png" class="img-fluid" width="450"></p>
<p>15.24 Notice that in the diagram in Exercise 15.28 SuppTotl has both a direct and an indirect effect on Depression. Its direct effect is the arrow that goes from SuppTotl to DepressT. The indirect effect (which here is not significant) comes from the fact that SuppTotl influences PVLoss, which in turn affects DepressT. Explain these direct and indirect effects in terms of semipartial regression coefficients.</p>
<p>15.25 A compulsive researcher who wants to cover all possibilities might throw in the total score on perceived vulnerability (PVTotal) as well as PVLoss. (The total includes vulnerability to accidents, illness, and life-style related problems.)</p>
<ol type="a">
<li>Run this analysis adding PVTotal to the variables used in Exercise 15.26.</li>
<li>What effect did the inclusion of PVTotal have on <span class="math inline">\(R^2\)</span>? What effect did it have on the standard error of the regression coefficient for PVLoss? If your program will also give you tolerance and VIF, what effect does the inclusion of PVTotal have on them?</li>
<li>What would you conclude about the addition of PVTotal to our model?</li>
</ol>
<p>15.29 Repeat the analysis of Exercise 15.26, requesting statistics on regression diagnostics.</p>
<ol type="a">
<li>What, if anything, do these statistics tell you about the data set?</li>
<li>Delete the subject with the largest measure of influence (usually indexed by Cook’s D). What effect does that have for this particular data set?</li>
</ol>
</section>
<section id="b.-malcarne-compas-epping-and-howell-1995" class="level3">
<h3 class="anchored" data-anchor-id="b.-malcarne-compas-epping-and-howell-1995">B. Malcarne, Compas, Epping, and Howell (1995)</h3>
<p><strong>Pre-test, Post-test 변화</strong></p>
<p>Data: <a href="https://www.dropbox.com/s/8jsmgu7a8pfdoaz/Malcarne.csv?dl=1">Malcarne.csv</a></p>
<p><img src="images/malcarne.png" class="img-fluid" width="450"></p>
<p>15.36 Malcarne, Compas, Epping, and Howell (1995) examined 126 cancer patients soon after they were diagnosed with cancer and at a four-month follow-up. At the initial interviews (Time 1) they collected data on the patients’ current levels of distress (Distres1), the degree to which they attributed the blame for the cancer to the type of person they are (BlamPer), and the degree to which they attributed the cancer to the kind of behaviors in which they had engaged, such as smoking or high fat diets (BlamBeh). At the four-month follow-up (Time 2) the authors again collected data on the levels of psychological distress that the patients reported (Distres2). (They also collected data on a number of other variables, which do not concern us here.) The data are available on the Web site for this course and named Malcarne.dat.</p>
<ol type="a">
<li>What would you conclude if you attempt to predict Distres2 from Distres1 and BlamPer?</li>
<li>Why would I want to include Distres1 in the analysis for part a?</li>
<li>How would you interpret the results if you predict the difference between Distres2 and Distres1 instead of predicting Distres2 only?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>distress <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Howell/Malcarne.csv"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>distress <span class="ot">&lt;-</span> distress <span class="sc">|&gt;</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> Distres2 <span class="sc">-</span> Distres1)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>distress <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Distres1 Distres2 BlamBeh BlamPer  diff
     &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1       39       43       1       1     4
2       39       54       2       1    15
3       42       50       3       1     8
4       43       33       1       1   -10
5       43       39       3       3    -4
6       43       43       1       1     0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>mod_stress <span class="ot">&lt;-</span> <span class="fu">lm</span>(Distres2 <span class="sc">~</span> Distres1 <span class="sc">+</span> BlamPer <span class="sc">+</span> BlamBeh, <span class="at">data =</span> distress)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>mod_diff <span class="ot">&lt;-</span> <span class="fu">lm</span>(diff <span class="sc">~</span> Distres1 <span class="sc">+</span> BlamPer <span class="sc">+</span> BlamBeh, <span class="at">data =</span> distress)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">export_summs</span>(mod_stress, mod_diff) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              ────────────────────────────────────────────────────
                                    Model 1          Model 2      
                               ───────────────────────────────────
                (Intercept)           14.05 *&nbsp;&nbsp;        14.05 *&nbsp;&nbsp;  
                                      (5.78)&nbsp;&nbsp;&nbsp;        (5.78)&nbsp;&nbsp;&nbsp;  
                Distres1               0.64 ***        -0.36 ***  
                                      (0.10)&nbsp;&nbsp;&nbsp;        (0.10)&nbsp;&nbsp;&nbsp;  
                BlamPer                2.45 *&nbsp;&nbsp;         2.45 *&nbsp;&nbsp;  
                                      (1.05)&nbsp;&nbsp;&nbsp;        (1.05)&nbsp;&nbsp;&nbsp;  
                BlamBeh                0.27&nbsp;&nbsp;&nbsp;&nbsp;         0.27&nbsp;&nbsp;&nbsp;&nbsp;  
                                      (0.99)&nbsp;&nbsp;&nbsp;        (0.99)&nbsp;&nbsp;&nbsp;  
                               ───────────────────────────────────
                N                     74&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        74&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                R2                     0.43&nbsp;&nbsp;&nbsp;&nbsp;         0.20&nbsp;&nbsp;&nbsp;&nbsp;  
              ────────────────────────────────────────────────────
                *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.           

Column names: names, Model 1, Model 2</code></pre>
</div>
</div>
</section>
<section id="c.-guber-1999" class="level3">
<h3 class="anchored" data-anchor-id="c.-guber-1999">C. Guber (1999)</h3>
<p>Case study 2의 연장</p>
<ul>
<li>SAT 테스트보다 ACT 테스트에 대해 교육지출의 효과를 보는 것이 교육의 질에 대한 논의에서 더 타당할 수 있음.</li>
<li>두 모형을 비교해 보고 차이를 살펴보도록 하세요.</li>
<li>Data: <a href="https://www.dropbox.com/s/ezviy8cdz7039cn/ACT.csv?dl=1">ACT.csv</a></li>
</ul>
<p>15.40 This chapter we spent a lot of time with Guber’s study of educational expenditures and found that when we controlled for the percentage of students taking the SAT exam, Expend was not a significant predictor. However, the SAT is not a good dependent variable in discussing the quality of education in a state. Perhaps a ACT, which tests something somewhat different, is a better predictor. Use SPSS and the data set, which is available on the book’s Web site and named Tab15-1.dat, to answer that question. Be complete in your answer, examining the individual variables and the residuals.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../contents/regression1.html" class="pagination-link" aria-label="Simple Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Simple Regression</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../contents/case1.html" class="pagination-link" aria-label="Case Study 1">
        <span class="nav-page-text">Case Study 1</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>This work © 2024 by Sungkyun Cho is licensed under CC BY-NC-SA 4.0</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>