{
  "hash": "86543c29e9416b80a16024f534d6e986",
  "result": {
    "markdown": "---\ntitle: Categorical IVs\nsubtitle: 'Applied Multiple Regression/Correlation Analysis for the Behavioral Sciences by Jacob Cohen, Patricia Cohen, Stephen G. West, Leona S. Aiken'\ndate: 'Feb 17, 2023'\nauthor: Sungkyun Cho\nexecute:\n  warning: false\n  freeze: auto\nformat: \n   html:\n    df-print: tibble\n    #monofont: 'FiraCode-Regular'\n---\n\n::: {.cell}\n\n:::\n\n\n범주형 변수가 예측변수가 되는 경우, 범주형 변수는 숫자로 변환시켜 분석 가능 \n\n범주가 실험 조건이 되는 경우, 예를 들어 통제집단과 처치집단에 대해서 그 차이를 보는 경우, **실험연구**의 전통을 가진 ANOVA 프레임워크에서 다루어져 왔고 다양한 용어(ANCOVA, fatorial ANOVA, repeated ANOVA, MANOVA 등등)와 분석 방식이 행해져왔으나, **관찰연구**의 전통을 가진 회귀분석의 프레임워크 안에서 통합될 수 있음.\n\n범주를 숫자로 변환시키는 방식은 연구의 목적에 따라 여러 방식으로 coding할 수 있는데, 예를 들어 sequential coding, Helmert coding, effect coding 등등에 대해서는 책을 참고.  \n10.1 Alternative Coding Systems in Regression Analysis and Linear Models by Richard B. Darlington & Andrew F. Hayes\n\n앞서, 범주가 2개인 성별의 경우: 남자는 0, 여자는 1로 변형시키는 dummy coding으로 indicator variable을 만들어 사용했음\n\n# 범주형 변수로만 예측하는 경우\n\n범주가 3개 이상인 경우에 대해서 multiple regression을 통해 분석 가능.\n\n## Attitude toward abortion (ATA)\n종교에 따른 낙태에 대한 (긍정적) 태도의 차이  \n종교: 개신교, 카톡릭, 유대교, 기타\n\n::: {layout=\"[20, 80]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nata <- read_csv(\"data/c08e01dt.csv\")\nata\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 36 × 2\n   rel          ata\n   <chr>      <dbl>\n 1 Catholic      61\n 2 Other         78\n 3 Protestant    47\n 4 Catholic      65\n 5 Catholic      45\n 6 Other        106\n 7 Protestant   120\n 8 Catholic      49\n 9 Other         45\n10 Other         62\n# ℹ 26 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ata, aes(x = rel, y = ata)) +\n    geom_boxplot(fill = \"white\") +\n    geom_jitter(width= .1, size = 2, color = \"orangered\")\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n:::\n\n다음은 dummy coding을 하는데 기준이 되는 범주(**reference group**)를 무엇으로 하느냐에 따른 차이를 보여줌  \n일반적으로 범주가 N개이면 N-1개의 dummy variable이 필요함.  \n각각의 dummy variable은 membership를 나타내며, 해당 범주에 속하는 경우 1, 아닌 경우 0으로 coding됨.\n\n- 여기서는 Protestant를 reference로 하는 B번을 사용하는데\n- $C_1$ : Catholic인지 아닌지\n- $C_2$ : Jewish인지 아닌지\n- $C_3$ : Other인지 아닌지\n\n\n![](images/dummy.png){width=600}  \n&emsp;&emsp; *p.304*\n\n### 회귀 계수\n\n우선, 명목변수를 R의 `factor` 타입으로 변환\n\n- `rel`을 `factor`로 변환; 순서를 고려해서\n- `Protestant`를 **reference group**으로 지정하기 위해 첫번째 level로 지정\n\n::: {.cell}\n\n```{.r .cell-code}\nata <- ata |> \n    mutate(rel = factor(rel, levels = c(\"Protestant\", \"Catholic\", \"Jewish\", \"Other\")))\n```\n:::\n\n\nR에서 기본적으로 factor는 dummy coding으로 변환  \n실제 내부적으로 어떻게 변환되는지 확인해보면,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.matrix(~ rel, data = ata) |> bind_cols(ata[\"rel\"]) # bind two columns\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 36 × 5\n   `(Intercept)` relCatholic relJewish relOther rel       \n           <dbl>       <dbl>     <dbl>    <dbl> <fct>     \n 1             1           1         0        0 Catholic  \n 2             1           0         0        1 Other     \n 3             1           0         0        0 Protestant\n 4             1           1         0        0 Catholic  \n 5             1           1         0        0 Catholic  \n 6             1           0         0        1 Other     \n 7             1           0         0        0 Protestant\n 8             1           1         0        0 Catholic  \n 9             1           0         0        1 Other     \n10             1           0         0        1 Other     \n# ℹ 26 more rows\n```\n:::\n:::\n\n\n이전과 같은 방식으로 선형회귀모형을 세워 분석하면,  \nModel: `ata ~ rel`  \n$\\widehat{ata} = b_1 \\cdot relCatholic + b_2 \\cdot relJewish + b_3 \\cdot relOther + b_0$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod <- lm(ata ~ rel, data = ata) \nS(mod, brief = TRUE)  # S()는 summmary() 대체 (car 패키지)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   93.308      6.495  14.366 1.66e-15 ***\nrelCatholic  -32.641     10.155  -3.214  0.00298 ** \nrelJewish     10.192     11.558   0.882  0.38444    \nrelOther     -23.183     10.523  -2.203  0.03491 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 23.42 on 32 degrees of freedom\nMultiple R-squared: 0.3549\nF-statistic: 5.869 on 3 and 32 DF,  p-value: 0.002599 \n   AIC    BIC \n334.98 342.89 \n```\n:::\n:::\n\n\nFitted model:  \n$\\widehat{ata} = -32.6 \\cdot relCatholic + 10.2 \\cdot relJewish - 23.2 \\cdot relOther + 93.3$\n\n각 회귀계수의 의미는 실제 dummy variable의 값을 대입함으로써 추론할 수 있음.\n\n*Protestant:* &nbsp;&nbsp; $\\widehat{ata} = b_1(0) + b_2(0) + b_3(0) + b_0 = b_0 = 93.3 = M_{Protestant}~(reference ~group)$  \n&nbsp;&nbsp;&nbsp; *Catholic:* &nbsp;&nbsp; $\\widehat{ata} = b_1(1) + b_2(0) + b_3(0) + b_0 = b_1 + b_0 = -32.6 + 93.3 = M_{Catholic}$  \n&emsp;&nbsp; *Jewish:* &nbsp;&nbsp; $\\widehat{ata} = b_1(0) + b_2(1) + b_3(0) + b_0 = b_2 + b_0 = 10.2 + 93.3 = M_{Jewish}$  \n&emsp;&emsp; *Other:* &nbsp;&nbsp; $\\widehat{ata} = b_1(0) + b_2(0) + b_3(1) + b_0 = b_3 + b_0 = -23.2 + 93.3 = M_{Other}$\n\n따라서, 각 회귀계수는 기울기로 (마찬가지로) 해석해서 0에서 1로 증가할 때의 변화량으로 해석할 수 있음. 즉, \n\n- $b_1 = -32.6$ 은 카톡릭 신자는 개신교도($b_0$)에 비해 32.6 정도 낙태에 대한 부정적인 태도를 나타냈음.\n- $b_2 = 10.2$ 는 유대교도는 개신교도($b_0$)에 비해 10.2 정도 낙태에 대한 긍정적인 태도를 나타냈음.\n- $b_3 = -23.2$ 는 기타 종교는 개신교도($b_0$)에 비해 23.2 정도 낙태에 대한 부정적인 태도를 나타냈음.\n\n각 범주에 대한 예측값은 해당 범주의 평균과 같음.\n\nGraphical representation of the model\n\n::: {layout=\"[60, 40]\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n:::\n\n회귀계수에 대한 가설검정\n\n- 각 회귀계수에 대한 가설검정은 해당 범주와 reference group의 평균이 같은지에 대한 테스트\n- 다른 범주간의 평균 차이에 대한 가설검정은 reference group을 바꿔 테스트\n\n\n::: {.cell}\n\n```{.r .cell-code}\nS(mod, brief = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   93.308      6.495  14.366 1.66e-15 ***\nrelCatholic  -32.641     10.155  -3.214  0.00298 ** \nrelJewish     10.192     11.558   0.882  0.38444    \nrelOther     -23.183     10.523  -2.203  0.03491 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 23.42 on 32 degrees of freedom\nMultiple R-squared: 0.3549\nF-statistic: 5.869 on 3 and 32 DF,  p-value: 0.002599 \n   AIC    BIC \n334.98 342.89 \n```\n:::\n:::\n\nReference group를 잠시 변경하고자 한다면, `fct_relevel()` 함수를 사용\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_Catholic <- lm(ata ~ fct_relevel(rel, \"Catholic\"), data = ata)  # Catholic을 첫번째 level로 변경\nS(mod_Catholic, brief = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficients:\n                                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                              60.667      7.806   7.772  7.3e-09 ***\nfct_relevel(rel, \"Catholic\")Protestant   32.641     10.155   3.214  0.00298 ** \nfct_relevel(rel, \"Catholic\")Jewish       42.833     12.342   3.470  0.00151 ** \nfct_relevel(rel, \"Catholic\")Other         9.458     11.379   0.831  0.41202    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 23.42 on 32 degrees of freedom\nMultiple R-squared: 0.3549\nF-statistic: 5.869 on 3 and 32 DF,  p-value: 0.002599 \n   AIC    BIC \n334.98 342.89 \n```\n:::\n:::\n\n\n만약, 여러 조합에 대한 가설검증을 한번에 하고자 한다면, **multiple test**의 문제를 고려한 다양한 방식이 존재  \nChapter 11. Multiple Test 참고, *Regression Analysis and Linear Models by Richard B. Darlington & Andrew F. Hayes*\n\n- Bonferroni correction: 비교하는 조합의 수로 나누어서 유의수준을 보정  \n    ex. 3개라면 3으로 p-value를 곱한 후 0.05보다 작은지 확인 (95% 유의수준에서)  \n- emmeans 패키지의 `emmeans()` 함수는 적절한 방식으로 multiple test를 수행\n\n아래는 **모든 조합 (all pairwise)**에 대한 가설검정 결과\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nemmeans(mod, pairwise ~ rel)  # all pairwise\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$emmeans\n rel        emmean   SE df lower.CL upper.CL\n Protestant   93.3 6.50 32     80.1    106.5\n Catholic     60.7 7.81 32     44.8     76.6\n Jewish      103.5 9.56 32     84.0    123.0\n Other        70.1 8.28 32     53.3     87.0\n\nConfidence level used: 0.95 \n\n$contrasts\n contrast              estimate   SE df t.ratio p.value\n Protestant - Catholic    32.64 10.2 32   3.214  0.0150\n Protestant - Jewish     -10.19 11.6 32  -0.882  0.8142\n Protestant - Other       23.18 10.5 32   2.203  0.1441\n Catholic - Jewish       -42.83 12.3 32  -3.470  0.0078\n Catholic - Other         -9.46 11.4 32  -0.831  0.8393\n Jewish - Other           33.38 12.6 32   2.639  0.0585\n\nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n:::\n:::\n\n아래는 **reference group과의 차이**에 대한 가설검정 결과\n\n- dummy coding한 회귀 분석과 같은 비교 단, 보정된 p-value\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(mod, trt.vs.ctrl ~ rel)  # treatment vs. control 용어에서 유래\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$emmeans\n rel        emmean   SE df lower.CL upper.CL\n Protestant   93.3 6.50 32     80.1    106.5\n Catholic     60.7 7.81 32     44.8     76.6\n Jewish      103.5 9.56 32     84.0    123.0\n Other        70.1 8.28 32     53.3     87.0\n\nConfidence level used: 0.95 \n\n$contrasts\n contrast              estimate   SE df t.ratio p.value\n Catholic - Protestant    -32.6 10.2 32  -3.214  0.0084\n Jewish - Protestant       10.2 11.6 32   0.882  0.6926\n Other - Protestant       -23.2 10.5 32  -2.203  0.0910\n\nP value adjustment: dunnettx method for 3 tests \n```\n:::\n:::\n\n> The second part of the output shows all possible pairwise differences of adjusted means and provides p-values for t-tests adjusted for multiple comparisons using, in this instance, Tukey’s HSD (“honestly significant difference”) method (Bretz, Hothorn, & Westfall, 2011, Section 4.2). The emmeans () function chooses an appropriate multiple-comparison method depending on the problem.  \n> *An R Companion to Applied Regression by John Fox *\n\n\n### Measure of association\n\n각 더미 변수들과 낙태에 대한 태도와의 고유한 상관계수인 partial correlation에 대해서 논의하는 것은 복잡하나, 원래의 의미를 유지하고 있음.\n\n더 중요한 관심은 종교라는 변수를 3개의 더미 변수들의 **set**으로 보고, 3개의 변수들이 합쳐서 낙태에 대한 태도를 얼마나 설명해주는지에 대해 말할 수 있음. \n\n- 즉, $R^2$를 보면 0.35로 종교 변수는 낙태에 대한 태도 변량의 35%를 설명해준다고 해석할 수 있음.\n- 그 상관계수 $R = \\sqrt{0.35} = 0.60$ 은 종교과 낙태에 대한 태도와의 상관 정도(association)를 말해 줌.\n- *주의!* 각 범주의 비율이 상정한 모집단과 어느 정도 일치해야지 모집단에 대한 추정이 의미가 있음.\n\nANOVA 프레임워크에서 effect size를 뜻하는 $\\eta^2$는 $R^2$와 동일하며  \n보정된 값들인 $\\epsilon^2,~ \\omega^2$에 대해서 $\\epsilon^2 = R^2_{adj}$ \n\n- *Adjusted (shrunken)* $R^2$ 는 표본에서 biased된 통계치인 $R^2$를 보정한 값으로, 모집단에서의 true $R^2$을 추정하기 위한 노력.\n\n참고: [Effect Sizes for ANOVAs](https://cran.r-project.org/web/packages/effectsize/vignettes/anovaES.html)\n\n예를 들어, \n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(mod)  # library(effectsize)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n  Parameter  Eta2    CI CI_low CI_high\n  <chr>     <dbl> <dbl>  <dbl>   <dbl>\n1 rel       0.355  0.95  0.105       1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nomega_squared(mod)  # library(effectsize)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n  Parameter Omega2    CI CI_low CI_high\n  <chr>      <dbl> <dbl>  <dbl>   <dbl>\n1 rel        0.289  0.95 0.0492       1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nepsilon_squared(mod)  # library(effectsize)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n  Parameter Epsilon2    CI CI_low CI_high\n  <chr>        <dbl> <dbl>  <dbl>   <dbl>\n1 rel          0.294  0.95 0.0537       1\n```\n:::\n:::\n\n:::\n\n\n## Effect size\n\n효과의 크기를 표현하기 위해 다양한 방식이 존재하며, 이는 연구의 성격과 전달하고자 하는 바에 맞춰 선택.\n\n크게 두 클래스로 나눌 수 있는데,\n\n\\ 1. **r-family** (correlation-based)\n\n앞서 전개한 *r(R), parital r, semi-partial r, (adjusted) R squared* 등을 통해 종속변수와 독립변수들의 관계의 크기를 구현함.  \nANOVA 프레임워크에서는  $\\eta^2, ~\\epsilon^2,~ \\omega^2$ 로 표현됨.\n\n- 임금의 변량이 성별에 의해 50% 설명된다면, 즉 $R^2$ = .5 라면, 임금에 미치는 **성별의 효과**의 크기를 0.2로 표현할 수 있고,\n- 또는 임금과 성별이 $R$ = .7 정도의 상관을 갖는다고 그 효과를 표현할 수 있음.\n- 앞서 예에서는 종교가 낙태에 대한 태도를 36% 설명하므로, 종교가 낙태에 대한 생각에 미치는 효과의 크기는 0.36 정도라고 혹은 $R$을 이용해 0.6 정도 라고 말할 수 있음.\n\n\\ 2. **d-family** (difference-based)\n\n두 집단의 평균 차이 혹은 비율을 표현하는데, 보통 표준편차의 단위로 표현. 말하자면, 표준화된 차이(standardized difference)  \n대표적으로 Cohen's *d* (Hedges' *g*, Glass's *delta*)\n\n - |d|<0.2 \"negligible\", |d|<0.5 \"small\", |d|<0.8 \"medium\", 그 외 \"large\"\n\n- 예를 들어, 어떤 회사의 남녀의 연봉 차이가 $8000일 때, 그 자체로 연봉에 미치는 성별의 효과로 말할 수 있으나\n- 표준편차의 단위로 표현하는 것이 더 적절할 수 있음. 예를 들어 그 회사의 연봉의 편차가 $2000일 때와 $4,000일 때 남녀 연봉의 차이가 실제 주는 의미가 다름. 즉, $8000/$2000 = 4와 $8000/$4000 = 2가 되어 표준편차의 단위로 표현하면 더 의미가 있음. (또는 남녀 각각의 표준편차의 (weighted) 평균 (pooled standard deviation)으로 나눔)\n- 이 때, 어떤 표준편차로 나눌지는 연구내용에 맞춰 효과의 크기가 잘 전달되도록 선택.\n\n참고:  \nCohen, J. (1992). A power primer. Psychological Bulletin, 112, 155-159.  \nDavid C. Howell (2011). [Confidence Intervals on Effect Size](https://www.uvm.edu/~statdhtx/methods8/Supplements/MISC/Confidence%20Intervals%20on%20Effect%20Size.pdf)\n\n\nR에서 d-family 효과 크기를 계산하는 한 방법  \n구체적 계산식은 `help(cohens_d)` 참고\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_d(ata ~ rel,  # library(effectsize)\n    data = filter(ata, \n        rel %in% c(\"Protestant\", \"Catholic\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  Cohens_d    CI CI_low CI_high\n     <dbl> <dbl>  <dbl>   <dbl>\n1     1.37  0.95  0.404    2.30\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_d(ata ~ rel, \n    data = filter(ata, \n        rel %in% c(\"Protestant\", \"Jewish\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  Cohens_d    CI CI_low CI_high\n     <dbl> <dbl>  <dbl>   <dbl>\n1   -0.365  0.95  -1.34   0.615\n```\n:::\n:::\n\n:::\n\n# 범주형 변수와 연속 변수로 함께 예측하는 경우\n\n## Simpler model\n\n예제: 이타적인 성향이 인구밀도에 영향을 받을 것이라는 가설 하에 도시지역(city)과 그 주변도시(noncity)의 주민들을 조사 (p. 344)  \n이 때, 연구자는 인구밀도에 따른 이타성의 차이는 그저 두 지역의 neuroticism의 차이를 반영할 뿐일 수 있음을 의심한다고 하면,\n\n![](images/altruism0.png){width=800}\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism <- read_csv(\"data/c08e02dt.csv\")\naltruism\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 150 × 5\n   altruism   ses neuroticism area       city    \n      <dbl> <dbl>       <dbl> <chr>      <chr>   \n 1     69.1  66.7        61.0 small_town non-city\n 2     56.2  58.0        73.6 small_town non-city\n 3     65.6  36.3        41.2 small_town non-city\n 4     65.8  63.8        55.9 small_town non-city\n 5     63.1  46.1        46.4 small_town non-city\n 6     50.6  42.2        58.2 small_town non-city\n 7     63.5  54.4        54.6 small_town non-city\n 8     69.1  26.2        47.5 small_town non-city\n 9     69.9  50.6        59.0 small_town non-city\n10     49.0  31.9        49.0 small_town non-city\n# ℹ 140 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = city, y = altruism)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = city, y = neuroticism)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = neuroticism, y = altruism)) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> group_by(city) |> \n  summarise(\n    mean_altruism = mean(altruism), sd_altruism = sd(altruism),\n    mean_neuroticism = mean(neuroticism), sd_neuroticism = sd(neuroticism)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  city     mean_altruism sd_altruism mean_neuroticism sd_neuroticism\n  <chr>            <dbl>       <dbl>            <dbl>          <dbl>\n1 city              34.8        10.9             58.4          10.4 \n2 non-city          53.2        11.8             55.0           9.10\n```\n:::\n:::\n\n\n위 플랏에서 확인해 볼 수 있으며, 아래 상관계수를 통해서도 세 변수들 간의 상관관계가 있음을 확인할 수 있음.\n\n::: {.cell}\n\n```{.r .cell-code}\n# factor로 변환; label도 함께 지정\naltruism <- altruism |>\n    mutate(\n        city = factor(city,\n            levels = c(\"non-city\", \"city\"),\n            labels = c(\"noncity\", \"city\")\n        )\n    )\n```\n:::\n\n\n일반적으로 dummy variable과의 상관계수는 해석이 어려우나, 다음과 같은 방식으로 살펴볼 수 있음.\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism_dummy <- fastDummies::dummy_cols(altruism, \"city\")\nlowerCor(altruism_dummy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             altrs ses   nrtcs area* city* cty_n cty_c\naltruism      1.00                                    \nses          -0.02  1.00                              \nneuroticism  -0.25  0.12  1.00                        \narea*         0.68 -0.20 -0.20  1.00                  \ncity*        -0.61  0.28  0.17 -0.87  1.00            \ncity_noncity  0.61 -0.28 -0.17  0.87 -1.00  1.00      \ncity_city    -0.61  0.28  0.17 -0.87  1.00 -1.00  1.00\n```\n:::\n:::\n\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = neuroticism, y = altruism, color = city)) +\n  geom_point() +\n  geom_smooth(se = FALSE)\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  mutate(neurotic_cat = cut_interval(neuroticism, 3)) |>\n  ggplot(aes(x = city, y = altruism, fill = neurotic_cat)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n:::\n\n\n이제 `neuroticism`을 **통계적으로 통제**(control for, hold it constant, partial the effect of) 한 선형회귀모형을 세우면,  \n(ANOVA 프레임워크에서 ANCOVA라고도 함; analysis of covariance)\n\n::: {.callout-important}\n아래 선형모형의 중요한 전제는 `city`와 `altruism`의 관계가 `neuroticism` 정도에 따라 변하지 않을 것이라는 것임.  \n위 플랏으로부터 어느 정도 정당화될 수 있고, 추가적으로 통계적 검정를 통해 확인할 수 있음.\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmod <- lm(altruism ~ city + neuroticism, data = altruism)\nS(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: lm(formula = altruism ~ city + neuroticism, data = altruism)\n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  65.23452    5.45529  11.958  < 2e-16 ***\ncitycity    -17.62565    1.94617  -9.057 7.63e-16 ***\nneuroticism  -0.21939    0.09684  -2.266   0.0249 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 11.32 on 147 degrees of freedom\nMultiple R-squared: 0.3972\nF-statistic: 48.44 on 2 and 147 DF,  p-value: < 2.2e-16 \n    AIC     BIC \n1158.63 1170.68 \n```\n:::\n:::\n\n\n$\\widehat Y = -17.62 \\cdot city - .22 \\cdot neuroticism + 59.731$\n\nneuroticism을 **centering**한 후, 선형회귀모형을 세우면,\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jtools) # for center()\nmod <- lm(altruism ~ city + center(neuroticism), data = altruism)\nS(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: lm(formula = altruism ~ city + center(neuroticism), data = altruism)\n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          52.88494    1.16772  45.289  < 2e-16 ***\ncitycity            -17.62565    1.94617  -9.057 7.63e-16 ***\ncenter(neuroticism)  -0.21939    0.09684  -2.266   0.0249 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 11.32 on 147 degrees of freedom\nMultiple R-squared: 0.3972\nF-statistic: 48.44 on 2 and 147 DF,  p-value: < 2.2e-16 \n    AIC     BIC \n1158.63 1170.68 \n```\n:::\n:::\n\n$\\widehat Y = -17.62 \\cdot city - .22 \\cdot neuroticism_C + 52.88$\n\n**Adjusted mean**: predicted means for each group\n\n- 절편 52.88은 도시에 살지 않는 사람들(non city: 0)의 이타성의 **adjusted mean** (neuroticism을 통제했다는 의미에서)\n- 기울기 -17.62는 도시인과 아닌 사람간의 이타성의 **adjusted mean** 차이 (adjusted mean difference)\n- 도시인들에 대한 이타성의 **adjusted mean** = -17.62(1) -.22(0) + 52.88 = 35.26\n- 비도시인들에 대한 이타성의 **adjusted mean** = -17.62(0) -.22(0) + 52.88 = 52.88\n\n즉, `neuroticism`의 **효과가 제거되었을 때 (partial out)**, 혹은 그 효과만큼 `city`가 **조정받은 후 (adjusted for)**, 도시인과 아닌 사람들의 이타성은 각각 35.26, 52.88로 추정됨.\n\nPlot으로 표현하면: effect plot\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effects)\nplot(predictorEffects(mod))\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n`neuroticism`의 효과가 partial된 실제 값에 대해 플랏을 그리면: add-variable plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcPlots(mod, terms = \"city\", overlaid = FALSE)\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n위의 선형모형 $\\widehat Y = -17.62 \\cdot city - .22 \\cdot neuroticism_C + 52.88$이 예측하는 값을 플랏에 추가하면,\n\n- 두 라인의 기울기는 -.22로 \"동일\"하며, (동일해야 함!)\n- 그 간격은 도시인이 17.62 낮음\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = center(neuroticism), y = altruism, color = city)) +\n  geom_point() +\n  geom_smooth(se = FALSE, size = .3) +\n  geom_line(aes(y = mod$fitted.values), size = 1) # 모형의 예측값들\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n`neuroticism`이 평균일 때의 adjusted mean은 \n\n$\\widehat{Y}_{city} = -(17.62)(1) - (.22)(0.0) + 52.88 = adjusted ~ M_{city}$\n$\\widehat{Y}_{noncity} = -(17.62)(0) - (.22)(0.0) + 52.88 = adjusted ~ M_{noncity}$\n\n만약, centering하지 않은 식이라면 `neuroticism`의 평균값을 대입.\n\n**Partial association**\n\n`area`의 고유한 설명력을 파악하기 위해 partial association 대해 알아보는 방식은 \n\n- 모형의 비교를 통해 $R^2$의 변화를 살펴보는 방식: semi-partial (squared)\n- Set correlation을 통해 partial out된 상관계수를 계산하는 방식: partial (squared)\n- ANOVA 프레임워크에서 partial eta-squared를 계산하는 방식: semi-paritl, partial (squared)\n\n![](images/altruism2.png){width=350}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_reduced <- lm(altruism ~ neuroticism, data = altruism) # reduced model\n```\n:::\n\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nexport_summs(mod_reduced, mod, \n    error_format = \"({p.value})\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<table class=\"huxtable\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \" id=\"tab:unnamed-chunk-32\">\n<col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 1</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 2</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(Intercept)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">67.13 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">52.88 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">neuroticism</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.37 **&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">citycity</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-17.63 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">center(neuroticism)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.22 *&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.02)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">150&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">150&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.06&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.40&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"3\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n:::\n:::\n\n\n![](images/altruism3.png){width=330}\n:::\n\n$\\Delta R^2$ = 0.40 - 0.06 = 0.34 : semi-partical correlation squared\n\nANOVA의 프레임워크에서 `neuroticism`의 효과가 partial out된 $\\eta^2$  \n참고: [Effect Sizes for ANOVAs](https://cran.r-project.org/web/packages/effectsize/vignettes/anovaES.html)\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(car::Anova(mod), partial = TRUE)  # partial correlation squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Effect Size for ANOVA (Type II)\n\nParameter           | Eta2 (partial) |       95% CI\n---------------------------------------------------\ncity                |           0.36 | [0.26, 1.00]\ncenter(neuroticism) |           0.03 | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n:::\n:::\n\n\n**Set correlation**을 통해 partial out된 상관계수\n\n::: {.cell}\n\n```{.r .cell-code}\n# 우선 dummy variable을 생성\naltruism_dummy <- fastDummies::dummy_cols(altruism, \"city\")\naltruism_dummy |> head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 7\n  altruism   ses neuroticism area       city    city_noncity city_city\n     <dbl> <dbl>       <dbl> <chr>      <fct>          <int>     <int>\n1     69.1  66.7        61.0 small_town noncity            1         0\n2     56.2  58.0        73.6 small_town noncity            1         0\n3     65.6  36.3        41.2 small_town noncity            1         0\n```\n:::\n\n```{.r .cell-code}\n# neuroticism partialled out!\nsetCor(altruism ~ city_city - neuroticism, data = altruism_dummy)\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: setCor(y = altruism ~ city_city - neuroticism, data = altruism_dummy)\n\nMultiple Regression from raw data \nThe following variables were partialed out: neuroticism \n and are included in the calculation of df1 and df2\n\n DV =  altruism* \n             slope   se     t       p lower.ci upper.ci VIF Vy.x\n(Intercept)*  0.00 0.06  0.00 1.0e+00    -0.13     0.13   1 0.00\ncity_city*   -0.59 0.06 -9.06 7.6e-16    -0.72    -0.46   1 0.36\n\nResidual Standard Error =  0.78  with  147  degrees of freedom\n\n Multiple Regression\n           R   R2  Ruw R2uw Shrunken R2 SE of R2 overall F df1 df2        p\naltruism 0.6 0.36 0.61 0.38        0.35     0.06     82.02   1 147 7.63e-16\n```\n:::\n:::\n\n즉, partial correlation = 0.60, partial correlation squared = 0.36 (=$\\eta^2$)\n\n\n## Full model\n\n이타적인 성향이 인구밀도에 영향을 받을 것이라는 가설하에, 세 지역 (도시, 교외, 시골)의 주민들을 조사하는데,  neuroticism 뿐만 아니라 사회경제적 상태(SES)도 이타성과 관련이 있음을 고려하면,\n\n![](images/altruism.png){width=750}\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = area, y = altruism)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = ses, y = altruism)) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = area, y = neuroticism)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = ses, y = neuroticism)) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = area, y = ses)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n:::\n\n위 플랏에서 확인해 볼 수 있으며, 아래 상관계수를 통해서도 상관관계가 있음을 확인할 수 있음.  \n일반적으로 dummy variable과의 상관계수는 해석이 어려우나, 다음과 같은 방식으로 살펴볼 수 있음.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# factor로 변환; label도 함께 지정\naltruism <- altruism |>\n    mutate(\n        area = factor(area,\n            levels = c(\"small_town\", \"rural\", \"city\"),\n            labels = c(\"small\", \"rural\", \"city\")\n        )\n    )\n\naltruism_dummy <- fastDummies::dummy_cols(altruism, \"area\")\nlowerCor(altruism_dummy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            altrs ses   nrtcs area* city* ar_sm ar_rr ar_ct\naltruism     1.00                                          \nses         -0.02  1.00                                    \nneuroticism -0.25  0.12  1.00                              \narea*       -0.68  0.20  0.20  1.00                        \ncity*       -0.61  0.28  0.17  0.87  1.00                  \narea_small   0.55 -0.05 -0.17 -0.84 -0.45  1.00            \narea_rural   0.12 -0.23 -0.01 -0.10 -0.59 -0.46  1.00      \narea_city   -0.61  0.28  0.17  0.87  1.00 -0.45 -0.59  1.00\n```\n:::\n:::\n\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = neuroticism, y = altruism, color = area)) +\n  geom_point() +\n  geom_smooth(se = FALSE)\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  mutate(neurotic_cat = cut_interval(neuroticism, 3)) |>\n  ggplot(aes(x = area, y = altruism, fill = neurotic_cat)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  ggplot(aes(x = ses, y = altruism, color = area)) +\n  geom_point() +\n  geom_smooth(se = FALSE)\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naltruism |> \n  mutate(ses_cat = cut_interval(ses, 3)) |>\n  ggplot(aes(x = area, y = altruism, fill = ses_cat)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n:::\n\n\n이제 `neuroticism`과 `ses`을 **통계적으로 통제**(control for, hold it constant, partial the effect of) 한 선형회귀모형을 세우면, (ANCOVA라고도 함; analysis of covariance)\n\n::: {.callout-important}\n아래 선형모형의 중요한 전제는 `area`와 `altruism`의 관계가 `neuroticism` 또는 `ses`정도에 따라 변하지 않을 것이라는 것임.  \n위 플랏으로부터 어느 정도 정당화될 수 있고, 추가적으로 통계적 검정를 통해 확인할 수 있음.\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_full <- lm(altruism ~ area + neuroticism + ses, data = altruism)\nS(mod_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: lm(formula = altruism ~ area + neuroticism + ses, data = altruism)\n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  60.82541    6.12678   9.928  < 2e-16 ***\narearural   -10.21356    2.18807  -4.668 6.87e-06 ***\nareacity    -24.96670    2.24895 -11.102  < 2e-16 ***\nneuroticism  -0.19045    0.08967  -2.124   0.0354 *  \nses           0.19643    0.08333   2.357   0.0197 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 10.38 on 145 degrees of freedom\nMultiple R-squared: 0.4997\nF-statistic:  36.2 on 4 and 145 DF,  p-value: < 2.2e-16 \n    AIC     BIC \n1134.69 1152.76 \n```\n:::\n:::\n\n\nCentering한 모형\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_full_c <- lm(altruism ~ area + center(neuroticism) + center(ses), data = altruism)\nS(mod_full_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: lm(formula = altruism ~ area + center(neuroticism) + center(ses), data =\n         altruism)\n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          59.38972    1.68236  35.301  < 2e-16 ***\narearural           -10.21356    2.18807  -4.668 6.87e-06 ***\nareacity            -24.96670    2.24895 -11.102  < 2e-16 ***\ncenter(neuroticism)  -0.19045    0.08967  -2.124   0.0354 *  \ncenter(ses)           0.19643    0.08333   2.357   0.0197 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 10.38 on 145 degrees of freedom\nMultiple R-squared: 0.4997\nF-statistic:  36.2 on 4 and 145 DF,  p-value: < 2.2e-16 \n    AIC     BIC \n1134.69 1152.76 \n```\n:::\n:::\n\n\n::: {.callout-important}\n통계적으로 유의하지 않는다고 해서, 변수를 제거하는 것은 절대 아님!  \n위 모형은 명시적으로 `neurotism`을 통제한 상태, 즉 `neurotism`의 효과를 제거한 후 `area`의 효과를 본다는 것을 말해주고 있음.  \n반면, 다른 독립변수들과 상관관계가 없다면 모형에 포함(통제)하지 않는 것이 적절. (명시 후에)\n:::\n\n`neuroticism`과 `ses`가 통제되지 않은 모형과 비교하면,  \n또한 표준화된 모형과 비교하면,\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nmod_simple <- lm(altruism ~ area, data = altruism)\nexport_summs(mod_simple, mod_full_c, error_format = \"(p = {p.value})\", model.names = c(\"Simple\", \"Full Centered\"))\n```\n\n::: {.cell-output-display}\n```{=html}\n<table class=\"huxtable\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \" id=\"tab:unnamed-chunk-47\">\n<col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Simple</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Full Centered</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(Intercept)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">59.73 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">59.39 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">arearural</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-11.15 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-10.21 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">areacity</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-24.94 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-24.97 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">center(neuroticism)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.19 *&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">center(ses)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.20 *&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.02)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">150&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">150&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.47&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.50&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"3\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n:::\n\n```{.r .cell-code}\n# scale: 독립변수들을 표준화, transform.response: 종속변수를 표준화\nexport_summs(mod_simple, mod_full, scale = TRUE, transform.response = TRUE, error_format = \"(p = {p.value})\", model.names = c(\"Simple Std\", \"Full Std\"))\n```\n\n::: {.cell-output-display}\n```{=html}\n<table class=\"huxtable\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \" id=\"tab:unnamed-chunk-47\">\n<col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Simple Std</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Full Std</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(Intercept)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.92 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.90 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">arearural</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.77 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.71 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">areacity</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-1.72 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-1.72 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">neuroticism</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.13 *&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">ses</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.15 *&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(p = 0.02)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">150&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">150&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.47&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.50&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"3\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">All continuous predictors are mean-centered and scaled by 1 standard deviation.  *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n:::\n:::\n\n*mod_full_c:* $\\widehat Y = -10.21 \\cdot rural - 24.97 \\cdot city -0.190 \\cdot neuroticism_C + 0.196 \\cdot ses_C + 59.39$\n\n- 절편 59.39은 small town 사람들의 이타성의 **adjusted mean** (neuroticism & ses을 통제했다는 의미에서)\n- 기울기 -10.21은 small town과 rural 사람간의 이타성의 **adjusted mean** 차이 (adjusted mean difference)\n- 기울기 -24.97은 small town과 city 사람간의 이타성의 **adjusted mean** 차이 (adjusted mean difference)\n\n**Adjusted mean**: predicted means for each group\n\n- small town 사람들에 대한 이타성의 **adjusted mean** = -10.21(0) - 24.97(0) + 59.39 = 59.39\n- rural 사람들에 대한 이타성의 **adjusted mean** = -10.21(1) - 24.97(0) + 59.39 = 49.18\n- city 사람들에 대한 이타성의 **adjusted mean** = -10.21(0) - 24.97(1) + 59.39 = 34.42\n\n즉, `neuroticism`과 `ses`의 **효과가 제거되었을 때 (partial out)**, 혹은 그 효과만큼 `city`가 **조정받은 후 (adjusted for)**, 각 지역의 사람들의 이타성은 각각 59.39, 49.18, 34.42로 추정됨.\n\nPlot으로 표현하면: effect plot\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effects)\nplot(predictorEffects(mod_full, ~ area))\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n위의 선형모형 $\\widehat Y = -10.21 \\cdot rural - 24.97 \\cdot city -0.190 \\cdot neuroticism_C + 0.196 \\cdot ses_C + 59.39$ 이 예측하는 값을 플랏에 추가하면,\n\n- 세 라인의 기울기는 -0.19로 \"동일\"하며, (동일해야 함!)\n- 그 간격은 small town 사람들에 비해 rural 사람들이이 -10.21 낮고\n- 그 간격은 small town 사람들에 비해 city 사람들이이 -24.97 낮음\n\n::: {.callout-note collapse=\"true\"}\n#### code\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(modelr)\ngrid_city <- altruism |> data_grid(neuroticism, area = \"city\", .model = mod_full) |> \n  add_predictions(mod_full)\ngrid_rural <- altruism |> data_grid(neuroticism, area = \"rural\", .model = mod_full) |> \n  add_predictions(mod_full)\ngrid_small <- altruism |> data_grid(neuroticism, area = \"small\", .model = mod_full) |> \n  add_predictions(mod_full)\n\naltruism |> \n  ggplot(aes(x = neuroticism, y = altruism, color = area)) +\n  geom_point() +\n  geom_smooth(se = FALSE, size = .3) +\n  geom_line(data = grid_city, aes(y = pred), size = 1) + \n  geom_line(data = grid_rural, aes(y = pred), size = 1) + \n  geom_line(data = grid_small, aes(y = pred), size = 1)\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n`neuroticism`과 `ses`가 평균일 때의 adjusted mean은 위에서 계산한 바와 같이\n\n- small town 사람들에 대한 이타성의 **adjusted mean** = -10.21(0) - 24.97(0) + 59.39 = 59.39\n- rural 사람들에 대한 이타성의 **adjusted mean** = -10.21(1) - 24.97(0) + 59.39 = 49.18\n- city 사람들에 대한 이타성의 **adjusted mean** = -10.21(0) - 24.97(1) + 59.39 = 34.42\n\n만약, centering하지 않은 식이라면 `neuroticism`과 `ses` 평균값을 대입.\n\n\n**Partial association**\n`area`의 고유한 설명력을 파악하기 위해 partial association 대해 알아보는 방식은 \n\n- 모형의 비교를 통해 $R^2$의 변화를 살펴보는 방식: semi-partial (squared)\n- Set correlation을 통해 partial out된 상관계수를 계산하는 방식: partial (squared)\n- ANOVA 프레임워크에서 partial eta-squared를 계산하는 방식: semi-paritl, partial (squared)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_full_reduced <- lm(altruism ~ neuroticism + ses, data = altruism) # reduced model\n```\n:::\n\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nexport_summs(mod_full_reduced, mod_full, \n    error_format = \"({p.value})\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<table class=\"huxtable\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \" id=\"tab:unnamed-chunk-52\">\n<col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 1</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 2</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(Intercept)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">66.88 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">60.83 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">neuroticism</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.37 **&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.19 *&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">ses</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.20 *&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.95)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.02)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">arearural</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-10.21 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">areacity</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-24.97 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">150&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">150&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.06&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.50&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"3\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n:::\n:::\n\n\n![](images/altruism4.png){width=350}\n:::\n\n$\\Delta R^2$ = 0.50 - 0.06 = 0.44 : semi-partical correlation squared\n\nANOVA의 프레임워크에서 `neuroticism`과 `ses`의 효과가 partial out된 $\\eta^2$  \n참고: [Effect Sizes for ANOVAs](https://cran.r-project.org/web/packages/effectsize/vignettes/anovaES.html)\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(car::Anova(mod_full), partial = TRUE)  # partial correlation squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Effect Size for ANOVA (Type II)\n\nParameter   | Eta2 (partial) |       95% CI\n-------------------------------------------\narea        |           0.47 | [0.37, 1.00]\nneuroticism |           0.03 | [0.00, 1.00]\nses         |           0.04 | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n:::\n:::\n\n\n**Set correlation**을 통해 partial out된 상관계수\n\n::: {.cell}\n\n```{.r .cell-code}\n# 우선 dummy variable을 생성\naltruism_dummy <- fastDummies::dummy_cols(altruism, \"area\")\naltruism_dummy |> head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 8\n  altruism   ses neuroticism area  city    area_small area_rural area_city\n     <dbl> <dbl>       <dbl> <fct> <fct>        <int>      <int>     <int>\n1     69.1  66.7        61.0 small noncity          1          0         0\n2     56.2  58.0        73.6 small noncity          1          0         0\n3     65.6  36.3        41.2 small noncity          1          0         0\n```\n:::\n\n```{.r .cell-code}\n# neuroticism & sex partialled out!\nsetCor(altruism ~ area_rural + area_city - neuroticism - ses, data = altruism_dummy)\n```\n\n::: {.cell-output-display}\n![](categorical_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: setCor(y = altruism ~ area_rural + area_city - neuroticism - \n    ses, data = altruism_dummy)\n\nMultiple Regression from raw data \nThe following variables were partialed out: neuroticism ses \n and are included in the calculation of df1 and df2\n\n DV =  altruism* \n             slope   se      t       p lower.ci upper.ci  VIF  Vy.x\n(Intercept)*  0.00 0.06   0.00 1.0e+00    -0.12     0.12 1.00  0.00\narea_rural*  -0.34 0.07  -4.67 6.9e-06    -0.49    -0.20 1.47 -0.04\narea_city*   -0.83 0.08 -11.10 4.1e-21    -0.98    -0.69 1.47  0.51\n\nResidual Standard Error =  0.72  with  145  degrees of freedom\n\n Multiple Regression\n            R   R2  Ruw R2uw Shrunken R2 SE of R2 overall F df1 df2       p\naltruism 0.68 0.47 0.41 0.17        0.45     0.06     63.58   2 145 1.5e-20\n```\n:::\n:::\n\n즉, partial correlation = 0.68, partial correlation squared = 0.47 (=$\\eta^2$)\n\n\n## 기타 예들\n\n- 정치학자가 인종 (black, hispanic, white), 성별, 가족 소득 수준이 정치적 태도에 미치는 영향을 연구하고자 할 때,\n- 교육학자가 공립학교와 사립학교의 수학 성취도를 비교하고자 하는데, 가족 소득 수준을 고정(통제)시키고자 할 때,\n\n# Exercises\n\ndata: [c0904dt.csv](https://www.dropbox.com/s/uqrblcc9aeq2gyc/c0904dt.csv?dl=1)\n\n1. 우선, 이전 분석에서처럼 관심이 연차(`time`)의 연봉에 대한 효과에 있다면, 나머지 변수들은 모두 고정(통제)시켜 분석해보고 그 의미를 해석해보세요.\n\n2. 각 부서별(`depart`)로 임금의 차이가 있는가에 대한 분석을 하고자 하는데 연차(`time`)와 논문수(`pub`), 성별(`sex`)를 고려해서 분석. 즉, 연차와 논문수, 성별을 고정한 후, 또는 그들의 효과를 제거 혹은 통제하고자 함.  \n\n3. 성별(`sex`)에 따른 임금의 차이가 있는가에 대한 분석을 하고자 하는데 연차(`time`)와 논문수(`pub`), 부서(`depart`)를 고려해서 분석. 즉, 연차와 논문수, 부서을 고정한 후, 또는 그들의 효과를 제거 혹은 통제하고자 함.  \n\n분석하면서 변수들의 효과에 대한 의미를 새기면서 분석을 해보세요.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacad3 <- read_csv(\"data/c0904dt.csv\")\nacad3 <- acad3 |> \n    mutate(depart = factor(depart, labels = c(\"psych\", \"soc\", \"hist\")),\n           sex = factor(sex, labels = c(\"male\", \"female\")))\nacad3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 150 × 5\n   depart   pub  time salary sex   \n   <fct>  <dbl> <dbl>  <dbl> <fct> \n 1 soc       16     3 56465. male  \n 2 soc       25     7 92044. female\n 3 soc       16     2 48980. male  \n 4 soc       24     1 53239. male  \n 5 soc       24     8 98948. female\n 6 soc       26    14 64782. female\n 7 soc       39     5 91652. female\n 8 soc       16     1 32833. female\n 9 soc       26    10 79231. female\n10 soc       23    11 77154. male  \n# ℹ 140 more rows\n```\n:::\n:::",
    "supporting": [
      "categorical_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}