{
  "hash": "d0ccd2a389d8a1049c30efe702bdbff3",
  "result": {
    "markdown": "---\ntitle: Interaction Effects\nsubtitle: 'Applied Multiple Regression/Correlation Analysis for the Behavioral Sciences by Jacob Cohen, Patricia Cohen, Stephen G. West, Leona S. Aiken'\ndate: 'Feb 17, 2023'\nauthor: Sungkyun Cho\nexecute:\n  warning: false\n  freeze: auto\nformat: \n   html:\n    df-print: tibble\n   # monofont: 'FiraCode-Regular'\n---\n\n::: {.cell}\n\n:::\n\n\n- 두 예측변수를 동시에 보고, regression plane의 입장에서 보았을 때\n- 한 예측변수가 변할 때, 다른 예측변수와 Y의 관계를 보았을 때\n\n## Continuous vs. Continuous\n\n예제: 나이가 듦(age)에 따른 지구력(endurance)의 감소가 운동을 한 기간(exercise)에 따라 변화하는가?\n\n- 연구자의 관심변수에 따라 다르게 표현될 수 있음.\n- 나이가 지구력에 미치는 부정적 영향을 운동이 완화시키는지 관심.\n- 이 때, 운동이 moderator로 작용하는 moderating effect (조절효과)를 가지는지 검증.\n- 통계적으로는 나이과 운동기간이 서로 상호작용(interact)하여 지구력에 영향을 미치는 것으로 나타남. \n\nData: [c07e01dt](https://www.dropbox.com/s/now7g6syjuhhghn/c07e01dt.csv?dl=1)\n\n`endurance`: the number of minutes of sustained jogging on a treadmill  \n`exercise`: the number of years of vigorous physical exercise\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nacad2 <- read_csv('cohen/data/c07e01dt.csv')\nacad2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 245 × 3\n     age exercise endurance\n   <dbl>    <dbl>     <dbl>\n 1    60       10        18\n 2    40        9        36\n 3    29        2        51\n 4    47       10        18\n 5    48        9        23\n 6    42        6        30\n 7    55        8         8\n 8    43       19        40\n 9    39        9        28\n10    51       14        15\n# ℹ 235 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(psych)\nlowerCor(acad2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          age   exrcs endrn\nage        1.00            \nexercise   0.28  1.00      \nendurance -0.13  0.34  1.00\n```\n:::\n:::\n\n:::\n\n::: {layout=\"[1, 1]\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nacad2 %>% \n  ggplot(aes(x = age, y = endurance)) +\n  geom_point() +\n  geom_smooth(se = FALSE, span = 1)\n```\n\n::: {.cell-output-display}\n![](interaction_files/figure-html/unnamed-chunk-4-1.png){width=384}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacad2 %>% \n  ggplot(aes(x = exercise, y = endurance)) +\n  geom_point() +\n  geom_smooth(se = FALSE, span = 1)\n```\n\n::: {.cell-output-display}\n![](interaction_files/figure-html/unnamed-chunk-5-1.png){width=384}\n:::\n:::\n\n:::\n\n나이와 지구력의 관계가 운동기간에 따라 다른가를 보기 위해, 운동기간을 3구간으로 나눔.\n\n::: {.cell}\n\n```{.r .cell-code}\n# 편의상 운동기간을 3구간으로 나눔\nacad2 %>% \n  mutate(exercise_cat = cut_number(exercise, 3)) %>% \n  ggplot(aes(x = age, y = endurance, color = exercise_cat)) +\n  geom_point() +\n  geom_smooth(se = FALSE, span = 1) +\n  facet_wrap(~exercise_cat)\n```\n\n::: {.cell-output-display}\n![](interaction_files/figure-html/unnamed-chunk-6-1.png){width=864}\n:::\n\n```{.r .cell-code}\n# 편의상 나이를 3구간으로 나눔\nacad2 %>% \n  mutate(age_cat = cut_number(age, 3)) %>% \n  ggplot(aes(x = exercise, y = endurance, color = age_cat)) +\n  geom_point() +\n  geom_smooth(se = FALSE, span = 1) +\n  facet_wrap(~age_cat)\n```\n\n::: {.cell-output-display}\n![](interaction_files/figure-html/unnamed-chunk-6-2.png){width=864}\n:::\n:::\n\n\n두 변수, 나이와 운동기간으로 지구력을 예측하는 모형을 세우면,\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_s1 <- lm(endurance ~ age, data = acad2)\nmod_s2 <- lm(endurance ~ exercise, data = acad2)\nmod <- lm(endurance ~ age + exercise, data = acad2)\nexport_summs(mod_s1, mod_s2, mod)\n```\n\n::: {.cell-output-display}\n```{=html}\n<table class=\"huxtable\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \" id=\"tab:unnamed-chunk-7\">\n<col><col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 1</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 2</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 3</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(Intercept)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">33.16 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">18.39 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">29.40 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(3.42)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(1.60)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(3.21)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">age</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.13 *&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.26 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.07)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.07)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">exercise</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.76 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.92 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">245&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">245&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">245&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.02&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.11&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.17&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"4\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n:::\n:::\n\n\nInteraction term을 추가해서 모형을 세우면\n\n$\\displaystyle \\widehat{endurance} = b_1\\cdot age + b_2\\cdot exercise + b_3\\cdot age \\cdot exercise + b_0$  \n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;$\\displaystyle = (b_1 + b_3 \\cdot exercise)\\cdot age + b_2\\cdot exercise + b_0$  \n이제 `age`의 기울기가 `exercise`의 값에 따라 변할 수 있음.\n\n::: {layout=\"[1, 1]\"}\n![](images/plot3d.png){width=370}\n\n![](images/plot3d2.png){width=350}\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_interact <- lm(endurance ~ age * exercise, data = acad2)  \n# 동일: endurance ~ age + exercise + age:exercise\nS(mod_interact) # library(car)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: lm(formula = endurance ~ age * exercise, data = acad2)\n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  53.17896    7.52661   7.065 1.71e-11 ***\nage          -0.76596    0.15980  -4.793 2.87e-06 ***\nexercise     -1.35095    0.66626  -2.028 0.043694 *  \nage:exercise  0.04724    0.01359   3.476 0.000604 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 9.7 on 241 degrees of freedom\nMultiple R-squared: 0.2061\nF-statistic: 20.86 on 3 and 241 DF,  p-value: 4.764e-12 \n    AIC     BIC \n1814.57 1832.07 \n```\n:::\n:::\n\n$\\displaystyle \\widehat{endurance} = -0.766\\cdot age -1.350\\cdot exercise + 0.047\\cdot age \\cdot exercise + 53.18$  \n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;$\\displaystyle = (-0.766 + 0.047 \\cdot exercise)\\cdot age -1.350\\cdot exercise + 53.18$  \n\n- `age`의 기울기는 `exercise`의 값에 따라 변함\n- 운동기간이 0년인 경우, 지구력에 미치는 나이의 효과: $(-0.766+0.047*0)\\cdot age = -0.766\\cdot age$\n- 운동기간이 10년인 경우, 지구력에 미치는 나이의 효과: $(-0.766+0.047*10)\\cdot age = -0.30\\cdot age$\n\n각 회귀계수의 의미는 다른 변수의 값이 0일 때의 기울기/효과임\n\n- `age`: -0.766은 운동기간이 0년일 때의 나이의 효과\n- `exercise`: -1.350은 나이가 0살일 때의 운동기간의 효과\n- `age:exercise`: 0.047는 두 변수의 joint effect\n- 절편 53.18: 운동기간이 0년인 0세의 지구력\n\n회귀계수를 용이하게 해석하기 위해 변수를 **centering**하거나 **standardizing**하는 것이 좋음.\n\n- 0의 의미가 있는 특별한 경우가 아니면 centering을 기본적으로 함. \n- 예를 들어, 언어발달 ~ 나이 * 형제자매 수 + 부모의 교육수준\n  - 형제자매의 수 0은 의미가 있음. \n- 위의 경우 `age`와 `exercise`의 단위가 의미가 있으므로, 표준화보다는 centering\n- p-value들은 모두 바뀐 의미의 회귀계수에 대한 영가설 검정\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# jtools의 center()함수를 이용하거나 데이터셋에서 미리 변환\nmod_interact_c <- lm(endurance ~ center(age) * center(exercise), data = acad2)\nS(mod_interact_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: lm(formula = endurance ~ center(age) * center(exercise), data = acad2)\n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  25.88872    0.64662  40.037  < 2e-16 ***\ncenter(age)                  -0.26169    0.06406  -4.085 6.01e-05 ***\ncenter(exercise)              0.97272    0.13653   7.124 1.20e-11 ***\ncenter(age):center(exercise)  0.04724    0.01359   3.476 0.000604 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 9.7 on 241 degrees of freedom\nMultiple R-squared: 0.2061\nF-statistic: 20.86 on 3 and 241 DF,  p-value: 4.764e-12 \n    AIC     BIC \n1814.57 1832.07 \n```\n:::\n:::\n\n- 나이에 대한 회귀계수 -0.26: 운동기간이 평균(10.67년)일 때의 나이의 효과\n- 운동기간에 대한 회귀계수 0.97: 나이가 평균(49.18세)일 때의 운동기간의 효과\n\n\n::: {.cell}\n\n```{.r .cell-code}\npsych::describe(acad2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          vars   n  mean    sd median trimmed   mad min max range skew kurtosis\nage          1 245 49.18 10.11     48   49.11 10.38  20  82    62 0.15    -0.08\nexercise     2 245 10.67  4.78     11   10.56  4.45   0  26    26 0.27     0.23\nendurance    3 245 26.53 10.82     27   26.39 10.38   0  55    55 0.11    -0.30\n            se\nage       0.65\nexercise  0.31\nendurance 0.69\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effects)\nplot(predictorEffects(mod_interact, ~age, xlevels = 3))\n```\n\n::: {.cell-output-display}\n![](interaction_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\nm <- mean(acad2$exercise) |> round(2); sd <- sd(acad2$exercise) |> round(2)\nplot(predictorEffects(mod_interact, ~age, xlevels = list(exercise = c(m-sd, m, m+sd))))\n```\n\n::: {.cell-output-display}\n![](interaction_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n:::\n\n평균보다 1 표준편차 만큼 오랜 운동한 경우: m + 1sd = 10.67 + 4.78 = 15.45년\n\n- 나이에 따른 지구력 감소가 거의 없는가?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_interact_t <- lm(endurance ~ age * I(exercise - 15.45), data = acad2)\nS(mod_interact_t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: lm(formula = endurance ~ age * I(exercise - 15.45), data = acad2)\n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             32.30671    4.72744   6.834 6.71e-11 ***\nage                     -0.03602    0.09027  -0.399 0.690184    \nI(exercise - 15.45)     -1.35095    0.66626  -2.028 0.043694 *  \nage:I(exercise - 15.45)  0.04724    0.01359   3.476 0.000604 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard deviation: 9.7 on 241 degrees of freedom\nMultiple R-squared: 0.2061\nF-statistic: 20.86 on 3 and 241 DF,  p-value: 4.764e-12 \n    AIC     BIC \n1814.57 1832.07 \n```\n:::\n\n```{.r .cell-code}\nconfint(mod_interact_t) |> print(digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        2.5 % 97.5 %\n(Intercept)             22.99 41.619\nage                     -0.21  0.142\nI(exercise - 15.45)     -2.66 -0.039\nage:I(exercise - 15.45)  0.02  0.074\n```\n:::\n:::\n\n\n\n\nInteraction의 패턴\n\n- synergistic or enhancing\nWhen both the first-order and interactive effects are of the same sign, the interaction is synergistic or enhancing. If all three signs are negative, we have the same synergistic effect. Suppose life satisfaction (Y) is negatively related to job stress (X) and to level of marital problems (Z).Their interaction is negative, so that having both high job stress and high marital problems leads to even less life satisfaction than the sum of X and Z would predict.\n\n- buffering interaction, \nalready defined in Section 7.4.5. Here the two predictors have regression coefficients of opposite sign. In addition, one predictor weakens the effect of the other predictor; that is, as the impact of one predictor increases in value, the impact of the other predictor is diminished. Buffering interactions are discussed in both mental and physical health research in which one predictor may represent a risk factor for mental or physical illness while the other predictor represents a protectivefactor that mitigates the threat of the risk factor (e.g., Cleary & Kessler, 1982; Cohen & Wills, 1985; Krause, 1995). In the second numerical example in this chapter, increasing age (X) is the risk factor for diminished endurance (F) and vigorous exercise is the protective factor (Z); the negative impact of age on endurance is lessened by a history of vigorous exercise.\n\n- interference orantagonistic interactionin\nwhich both predictors work on the criterion in the same direction, and the interaction is of opposite sign (Neter, Kutner, Nachtsheim, & Wasserman, 1996). Recall the example mentioned at the outset of Section 7.1, that perhaps ability and motivation have compensatory effects on graduate school achievement. Surely both ability and motivation are each positively related to achieve- ment (Bl > 0 and B2 > 0). Yet the importance of exceptional ability may be lessened by exceptional motivation, and vice versa, a partially \"either-or\" pattern of influence of the two predictors on the criterion. If so, their interaction is negative (B3 < 0), that is, of the opposite sign of the two first-order effects.\n\n\n- Hassles, support, symptons p.551 Howell\n\n\n\n## Continuous vs. Categorical\n\n- 부서별 연봉\n- 성별\n- Demetia 그룹에 따른\n\n\n## Categorical vs. Categorical: factorrical design\n\n- 성별과 결혼 여부에 따른 임금차이",
    "supporting": [
      "interaction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}