{
  "hash": "63bd6cdade053d08423cfa9852375b3c",
  "result": {
    "markdown": "---\ntitle: Multiple Regression\nsubtitle: 'Applied Multiple Regression/Correlation Analysis for the Behavioral Sciences by Jacob Cohen, Patricia Cohen, Stephen G. West, Leona S. Aiken'\ndate: 'Feb 17, 2023'\nauthor: Sungkyun Cho\nexecute:\n  warning: false\n  freeze: auto\nformat: \n   html:\n    df-print: tibble\n---\n\n::: {.cell}\n\n:::\n\n\n# Multiple linear/regression models\n\n- 독립/예측 변수가 2개 이상인 경우\n- 예측변수들 각각의 **고유한 효과**(effect)를 추정(estimate)\n- 이는 다른 변수들의 영향이 제거된 해당 변수의 효과는 어떠한가를 의미\n\n\n앞서 논의된 내용은 두 변수 사이의 관계를 다룸으로써 비교적 단순한 추론 및 두 변수 간에 모종의 관계의 유무(영가설) 정도를 살펴보았음.  \n\n3개 이상의 변수 간의 관계에 대해서는 기하급수적으로 복잡한 관계가 나타남으로 인해, 연구자는 영향을 주고 받는 변수들 간의 **인과 관계**에 대해 충분한 이론적 근거를 갖고, 분석의 목적을 분명히 할 필요가 있음. (탐색적 분석이나 단순한 예측을 위한 것이 아니라면)\n\n인과분석은 유전학자였던 Sewell Wright(1921)가 유전적 효과와 비유전적 효과를 분리하려는 노력하에 개발했던 경로분석 다이어그램(path analytic diagram)에 그 뿌리를 두고 있으며, 후에 구조모형(structural model)으로 불리어 이어져 왔으며, causal analysis라는 분야에서 완성되어가고 있음.\n\n기본적인 인과관계의 프레임워크에서, X가 Y의 원인이기 위해서 다음 4가지 조건을 만족해야 함.\n\n- X는 시간적으로 Y에 선행\n- 인과적 효과를 만들어내는 기제(mechanism)를 상정할 수 있음\n- X가 변하면 Y도 변화가 발생함 (association or correlation)\n  - X를 변화시키면 Y가 변한다는 것은 뜻은 아님. \n    - 성별처럼 변화시킬 수 없는 요인도 있음\n    - X를 어떻게 manupulate 하느냐에 따라 정상적 기제가 변형되어 다른 효과가 나타날 수 있음.\n      - 임금을 갑자기 2배 올리면?\n      - 임금을 줄이면?\n- 다른 요인들 (confounding)을 제거한 후에도 X의 효과가 나타나야 함.\n  - 임금은 연령이 높을수록 높아지는데 삶의 만족도는 늙음으로부터 오는 정신적 여유에서 발생한 것이라면?\n\n> 인과관계는 통계적 분석에 의해 증명될 수 있는 것이 아니며,  \n> **관찰된 데이터와 상정한 모형이 어느 정도 일치한다**라고 말할 수 있는 정도에서 결론지을 수 있으며,  \n> 그 모형이 맞다면, 그 효과는 어떠하다고 실증적(empirically)으로 보이는 것임.  \n> 모형의 가치는 그 구조적 논리에 크게 좌우됨.\n\n앞서 다뤘던 교수의 연봉에 연차와 성과물이 영향을 미친다는 인과모형을 세우면,  \n\n- 연차와 성과물 간에 인과관계는 상정하지 않았음.\n- 적어도 연봉이 성과물이나 연차에 영향을 주지는 않는다고 상정했음.\n\n![](images/diagram2.png)\n\n교수의 연봉(`salary`)이 학위를 받은 후 지난 시간(`time` since Ph.D.)과 출판물의 수(`pubs`)에 의해 어떻게 영향을 받는가?\n\n-   같은 연차의 교수들 간에 논문 수에 따라 연봉은 얼마나 차이가 나는가?\n-   동일한 개수의 논문을 발표한 교수들 간에 연차에 따라 연봉은 얼마나 차이가 나는가?\n\n앞서 연봉에 대한 예측모형을 다음과 같이 얻었는데,\n\n-   Model 1: $\\widehat{salary} = \\$1,224\\:time + \\$43,659$\n-   Model 2 : $\\widehat{salary} = \\$336\\:pubs + \\$46,357$\n\n다음과 같이 연차가 늘면 논문의 수도 따라서 늘어나는 경향이 있기 때문에, 연차 또는 논문 수의 고유한 효과를 추정하기 어려움.\n\n-   $\\widehat{pubs} = 1.98\\:time + 4.73$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacad0 <- read_csv(\"data/c0301dt.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(salary ~ time, data = acad0)\nmod2 <- lm(salary ~ pubs, data = acad0)\n```\n:::\n\n\n### 두 개의 예측변수를 모두 포함한 모형\n\nModel 3: $\\widehat{Y} = a_1 X_1 + a_2 X_2 + a_0 ~ (z=2x-y+1)$\n\n$\\widehat{salary} = \\$983\\:time + \\$122\\:pubs + \\$43,082$\n\n::: {.cell layout-ncol=\"1\"}\n\n```{.r .cell-code}\nmod3 <- lm(salary ~ time + pubs, data = acad0)\nsumm(mod3)  # library(jtools)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 15 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> salary </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> OLS linear regression </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> F(2,12) </td>\n   <td style=\"text-align:right;\"> 6.78 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> R² </td>\n   <td style=\"text-align:right;\"> 0.53 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Adj. R² </td>\n   <td style=\"text-align:right;\"> 0.45 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 43082.39 </td>\n   <td style=\"text-align:right;\"> 3099.49 </td>\n   <td style=\"text-align:right;\"> 13.90 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> time </td>\n   <td style=\"text-align:right;\"> 982.87 </td>\n   <td style=\"text-align:right;\"> 452.06 </td>\n   <td style=\"text-align:right;\"> 2.17 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> pubs </td>\n   <td style=\"text-align:right;\"> 121.80 </td>\n   <td style=\"text-align:right;\"> 149.70 </td>\n   <td style=\"text-align:right;\"> 0.81 </td>\n   <td style=\"text-align:right;\"> 0.43 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: OLS</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\n\nThe regression plane: x값이 고정될 때, 혹은 y값이 고정될 때, **동일한 기울기**의 직선으로 나타남.  \n![](images/regression_plane.png){width=\"400\"}\n\n::: {.callout-note collapse=\"true\"}\n### 3d plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-5ca8c1bd78730824fef0\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5ca8c1bd78730824fef0\">{\"x\":{\"visdat\":{\"5edf6916debb\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"5edf6916debb\",\"attrs\":{\"5edf6916debb\":{\"x\":{},\"y\":{},\"z\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":[51876,54511,53425,61863,52926,47034,66432,61100,41934,47454,49832,47047,39115,59677,61458],\"colorscale\":[\"#FFE1A1\",\"#FF4304\"],\"size\":6},\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"pubs\"},\"yaxis\":{\"title\":\"time\"},\"zaxis\":{\"title\":\"salary\"}},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[18,3,2,17,11,6,38,48,9,22,30,21,10,27,37],\"y\":[3,6,3,8,9,6,16,10,2,5,5,6,7,11,18],\"z\":[51876,54511,53425,61863,52926,47034,66432,61100,41934,47454,49832,47047,39115,59677,61458],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":[51876,54511,53425,61863,52926,47034,66432,61100,41934,47454,49832,47047,39115,59677,61458],\"colorscale\":[\"#FFE1A1\",\"#FF4304\"],\"size\":6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n:::\n\n-   교수들의 연차와 그들이 쓴 논문 수는 깊이 연관되어 있으며 (*r* = 0.66), 두 변수의 redunancy가 각 변수들의 효과를 변화시킴.\n-   두 예측 변수의 산술적 합으로 연봉을 예측하므로 각 예측변수의 효과는 수정될 수 밖에 없음.\n-   수학적으로 보면, 각 예측변수의 기울기는 다른 예측변수의 값에 상관없이 일정하므로, 다른 예측변수들을 (임의의 값에) **고정시키는 효과**를 가짐\n-   즉, 다른 변수와는 독립적인, **고유한 효과**를 추정하게 됨\n\n세 모형을 비교하면,\n\nModel 1: $\\widehat{salary} = \\$1,224\\:time + \\$43,659$\\\nModel 2 : $\\widehat{salary} = \\$336\\:pubs + \\$46,357$\\\nModel 3: $\\widehat{salary} = \\$983\\:time + \\$122\\:pubs + \\$43,082$\n\n-   연차(`time`)의 효과는 \\$1,224에서 \\$984로 낮아졌고,\n-   논문수(`pubs`)의 효과는 \\$336에서 \\$122로 낮아졌음.\n\n각 회귀계수를 partial regression coefficient (부분 회귀 계수) 라고 부름.\n\n다른 변수가 **partial out** 된 후의 효과.  \n실제로 $122는 연차로 (선형적으로) 예측되지 않는 논문수(residuals)로 연봉을 예측할 때의 기울기\n\n- 해석은, 만약 논문 수가 일정할 때, 예를 들어 10편의 논문을 쓴 경우만 봤을 때, 연차가 1년 늘 때마다 연봉은 \\$984 증가함; 평면의 선형모형을 가정했기에 이 관계는 논문 수에 상관없음.  \n- 연차가 일정할 때, 예를 들어 연차가 12년차인 경우만 봤을 때, 논문이 1편 늘 때마다 연봉은 \\$336 증가함; 평면의 선형모형을 가정했기에 이 관계는 연차에 상관없음.\n\n이는 다른 **변수를 고려 (통제, controlling for) 했을 때 혹은 다른 변수의 효과를 제거 (partial out) 했을 때**, 각 변수의 **고유한 효과**를 의미함. (*holding constant* or *controlling for, partialing the effects of,* or *residualizing)*\n\n뒤집어 말하면, 연차만 고려했을때 연차가 1년 늘면 \\$1,224 연봉이 증가하는 효과는 연차가 늘 때 함께 늘어나는 논문 수의 효과가 함께 섞여 나온 효과라고 말할 수 있음.\n\n이는 인과관계에 있는 변수들의 진정한 효과를 찾는 것이 얼마나 어려운지를 보여줌\n\n![](images/salary_model1.png){fig-align=\"left\" width=\"410\"}\n\n> The partial regression coefficients, \\$983 and \\$122, are the empirical estimates, respectively, of h and g, the causal effects of our independent variables accompanying the arrows in the causal diagram (Fig. 3.1.1) (p. 69).\n\n논문 수($X_2$)에 대한 부분 회귀 계수에 대해 자세히 들여다 보면,\n\n&emsp; ![](images/partial1.png){width=\"260\"}\n\n$\\widehat{Y_1}: X_1$ 으로만 $Y$를 예측했을 때의 예측치, &nbsp; $\\widehat{Y}_{12}: X_1$과 $X_2$ 로 함께 $Y$를 예측했을 때의 예측치  \n$\\widehat{X}_{2.1}$: $X_1$ 으로 $X_2$ 를 예측했을 때의 예측치; 연차로 예측된 논문수  \n$X_2 - \\widehat{X}_{2.1}$: $X_1$으로 $X_2$를 예측했을 때의 예측하지 못한 잔차: 연차로 예측되지 않는 논문수  \n$Y-\\widehat{Y}_1$: $X_1$으로 예측되지 않는 $Y$ : 연차로 예측되지 않는 연봉\n\n논문 수($X_2$)에 대한 부분 회귀 계수: \\[연차로 예측되지 않는 논문 수\\]와 \\[연차로 예측되지 않는 연봉\\] 간의 선형관계에 대한 계수\n\n$\\widehat{salary} = \\$983\\:time + \\$122\\:pubs + \\$43,082$\n\n- $\\widehat{salary} = \\$1,224\\:time + \\$43,659$  \n- $\\widehat{pubs} = 1.98\\:time + 4.73$\n\n![](images/partial_regression.png){fig-align=\"left\" width=\"810\"}\n\n**Partial regression plots**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\navPlots(mod3)  # partial regression plot\n```\n\n::: {.cell-output-display}\n![](regression2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n## Measures of Association\n\n![](images/partial3.png){width=\"320\"}  \n$R$ : $Y$ 와 $\\widehat Y$ 의 correlation 즉, Y와 예측값의 (선형적) 상관 관계의 정도.  \n또는 예측변수들의 최적의 선형 조합과 Y의 상관 관계의 정도.\n\n$R^2$: (평면의) 선형모형에 의해 설명된 Y의 변량의 비율.  \n또는 예측변수들의 최적의 선형 조합에 의해 설명된 Y의 변량의 비율.\n\n**Partial Associations**\n\n- Partial correlation *(pr)*\n- Semi-partial correlation *(sr)*\n\n::: {layout-ncol=2} \n![](images/partial1.png){width=\"260\"}\n\n![](images/partial2.png){width=\"340\"}\n:::\n\n$pr^2$ : \"연차로 설명되지 않는 연봉\"의 변량 중 \"연차로 설명되지 않는 논문수\"의 변량으로 설명되는 비율  \n즉, 연차를 연봉과 논문수에서 모두 partial out 시켰을 때 남은(residualized) 연봉의 변량과 논문수의 변량의 중복 정도.\n\n$sr^2$ : 연봉의 변량 중 \"연차로 설명되지 않는 논문수\"의 변량으로 설명되는 비율  \n즉, 연차를 논문수에서만 partial out 시켰을 때 남은(residualized) 논문수의 변량과 연봉의 변량의 중복 정도.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumm(mod3, part.corr = TRUE, model.info = FALSE, model.fit = FALSE)\n```\n\n::: {.cell-output-display}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n   <th style=\"text-align:right;\"> partial.r </th>\n   <th style=\"text-align:right;\"> part.r </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 43082.39 </td>\n   <td style=\"text-align:right;\"> 3099.49 </td>\n   <td style=\"text-align:right;\"> 13.90 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> time </td>\n   <td style=\"text-align:right;\"> 982.87 </td>\n   <td style=\"text-align:right;\"> 452.06 </td>\n   <td style=\"text-align:right;\"> 2.17 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 0.53 </td>\n   <td style=\"text-align:right;\"> 0.43 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> pubs </td>\n   <td style=\"text-align:right;\"> 121.80 </td>\n   <td style=\"text-align:right;\"> 149.70 </td>\n   <td style=\"text-align:right;\"> 0.81 </td>\n   <td style=\"text-align:right;\"> 0.43 </td>\n   <td style=\"text-align:right;\"> 0.23 </td>\n   <td style=\"text-align:right;\"> 0.16 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: OLS</td></tr></tfoot>\n</table>\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n#### Correlations tables\n```r\nlibrary(psych)\npartial.r(acad0, c(\"salary\", \"time\"), \"pubs\")\n# partial correlations \n#        salary time\n# salary   1.00 0.53\n# time     0.53 1.00\n\npartial.r(acad0, c(\"salary\", \"pubs\"), \"time\")\n# partial correlations \n#        salary pubs\n# salary   1.00 0.23\n# pubs     0.23 1.00\n\ncor2(acad0[c(\"time\", \"pubs\")], acad0[\"salary\"])\n#      salary\n# time   0.71\n# pubs   0.59\n```\n:::\n\nCorrelations with `salary`\n\n::: {layout=\"[60, -2, 38]\"}\n|  | $r$ *(zero-order)* | $pr$ *(partial)* | $sr$ *(semi-partial)* |\n|:--------:|:---:|:---:|:---:|\n| time     | 0.71| 0.53| 0.43|\n| pubs     | 0.59| 0.23| 0.16|\n\n|  | $r^2$ | $pr^2$ | $sr^2$ |\n|:--------:|:---:|:---:|:---:|\n| time     | 0.50| 0.28| 0.18|\n| pubs     | 0.35| 0.05| 0.03|\n:::\n\n> Summarizing the results for the running example, we found $sr^2$ = .1850, $pr^2$ = .2826 and\n$sr^2$ = .0258, $pr^2$ = .0522. Whichever base we use, it is clear that number of publications ($X_2$) has virtually no unique relationship to salary, that is, no relationship beyond what can be accounted for by time since doctorate ($X_1$). On the other hand, time since doctorate ($X_1$) is uniquely related to salary ($sr_1$) and to salary holding publications constant ($pr_1$) to a quite substantial degree. (p.75)\n\n## 회귀계수의 상대적 중요성\n참고: Chapter 8. Assessing the Importance of Regressors,  \nin *Regression Analysis and Linear Models by Richard B. Darlington & Andrew F. Hayes*\n\n모든 상황에 적용할 수 있는 하나의 방법은 없으며,  \n연구 내용과 측정 변수들의 특성에 따라 적절한 방법을 선택. (여전히 논쟁 중이며, 새로운 방법 개발 중)\n\n- 표준화 회귀계수 (standardized regression coefficient)\n- **Semi-partial correlation** coefficient *(sr)* **\n- Dominance analysis\n\n### 표준화 회귀계수 ($\\beta$) \nStandardized regression coefficient\n\n- 표준화하여 각 변수들의 단위가 1sd로 같아져 계수들 간에 비교가 용이하나\n- 표준화는 현 표본의 특성을 반영할 뿐 아니라 표준화가 무의미한 변수들도 존재하여 표준화에 (심각하게) 반대하는 의견도 있음.\n\nR에서 표준화 계수를 구하는 방식: `scale()`, `lm.beta()`, `summ()`\n\n1. `scale()` 함수로 각 변수들을 직접 표준화  \n참고: 표준화 한 후 estimate한 방식 vs. estimate한 후 표준화한 방식\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacad0 <- acad0 |> \n  mutate(\n    time_std = scale(time),\n    pubs_std = scale(pubs),\n    salary_std = scale(salary)\n  )\n```\n:::\n\n또는 formula에서 직접 처리\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(lm(scale(salary) ~ scale(time) + scale(pubs), data = acad0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept) 2.37e-16     0.191  1.24e-15  1.00  \n2 scale(time) 5.70e- 1     0.262  2.17e+ 0  0.0504\n3 scale(pubs) 2.13e- 1     0.262  8.14e- 1  0.432 \n```\n:::\n:::\n\n2. `lm.beta()` 함수로 표준화 계수를 추가\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lm.beta)\nbroom::tidy(lm.beta(mod3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 6\n  term        estimate std_estimate std.error statistic       p.value\n  <chr>          <dbl>        <dbl>     <dbl>     <dbl>         <dbl>\n1 (Intercept)   43082.       NA         3099.    13.9   0.00000000926\n2 time            983.        0.570      452.     2.17  0.0504       \n3 pubs            122.        0.213      150.     0.814 0.432        \n```\n:::\n:::\n\n\n3. `summ()` 함수의 옵션 `scale`, `transform.response`을 이용\n\n- 선별적으로 표준화할 변수를 지정할 수 없어서 부적절한 경우 존재\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nsumm(mod3, scale = TRUE, transform.response = TRUE, model.info = FALSE, model.fit = FALSE)\n```\n\n::: {.cell-output-display}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n   <td style=\"text-align:right;\"> 0.19 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> time </td>\n   <td style=\"text-align:right;\"> 0.57 </td>\n   <td style=\"text-align:right;\"> 0.26 </td>\n   <td style=\"text-align:right;\"> 2.17 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> pubs </td>\n   <td style=\"text-align:right;\"> 0.21 </td>\n   <td style=\"text-align:right;\"> 0.26 </td>\n   <td style=\"text-align:right;\"> 0.81 </td>\n   <td style=\"text-align:right;\"> 0.43 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: OLS; Continuous variables are mean-centered and scaled by 1 s.d.</td></tr></tfoot>\n</table>\n:::\n:::\n\n\n\n## Model Comparison\n\n1. mod1 vs. mod3: nested model\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(salary ~ time, data = acad0)\nmod3 <- lm(salary ~ time + pubs, data = acad0)\n```\n:::\n\n\n::: {layout-ncol=2}\n- 연차로 연봉의 변량을 설명한 모형에 논문 수가 예측변수로 추가되었을 때, 추가로 연봉의 변량을 얼마나 설명하는가?\n- $R^2$의 증가량을 통해 파악할 수 있음.\n- $\\Delta R^2$ = 0.530 - 0.505 = 0.025\n- $sr^2$ 과 동일 (*semi-partial squared*)\n\n![](images/sp1.png){width=320}\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(mod1)  # library(broom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>   <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.505         0.466 5763.      13.2 0.00300     1  -150.  306.  308.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n:::\n\n```{.r .cell-code}\nglance(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>   <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.530         0.452 5839.      6.78  0.0107     2  -150.  307.  310.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n:::\n:::\n\n$\\Delta R^2$ 가 통계적으로 유의한지, 즉 유의하지 증가했는지를 확인\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod1, mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  Res.Df        RSS    Df `Sum of Sq`      F `Pr(>F)`\n   <dbl>      <dbl> <dbl>       <dbl>  <dbl>    <dbl>\n1     13 431731655.    NA         NA  NA       NA    \n2     12 409159359.     1   22572295.  0.662    0.432\n```\n:::\n:::\n\n<br>\n2. mod2 vs. mod3: nested model\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <- lm(salary ~ pubs, data = acad0)\nmod3 <- lm(salary ~ time + pubs, data = acad0)\n```\n:::\n\n\n::: {layout-ncol=2}\n- 논문수로 연봉의 변량을 설명한 모형에 연차가 예측변수로 추가되었을 때, 추가로 연봉의 변량을 얼마나 설명하는가?\n- $R^2$의 증가량을 통해 파악할 수 있음.\n- $\\Delta R^2$ = 0.530 - 0.346 = 0.184\n- $sr^2$ 과 동일 (*semi-partial squared*)\n\n![](images/sp2.png){width=320}\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(mod2)  # library(broom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>   <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.346         0.295 6624.      6.86  0.0212     1  -152.  310.  312.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n:::\n\n```{.r .cell-code}\nglance(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>   <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.530         0.452 5839.      6.78  0.0107     2  -150.  307.  310.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n:::\n:::\n\n$\\Delta R^2$ 가 통계적으로 유의한지, 즉 유의하지 증가했는지를 확인\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod2, mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  Res.Df        RSS    Df `Sum of Sq`     F `Pr(>F)`\n   <dbl>      <dbl> <dbl>       <dbl> <dbl>    <dbl>\n1     13 570340401.    NA         NA  NA     NA     \n2     12 409159359.     1  161181042.  4.73   0.0504\n```\n:::\n:::\n\n\n## Patterns of Association\n\n### Direct and Indirect Effects\n\n만약, 다음과 같은 인과모형을 세운다면,\n\n![](images/salary_model2.png){width=450}\n\n- 연차가 연봉에 미치는 효과가 두 경로로 나뉘어지고,\n- 연차 $\\rightarrow$ 연봉: **직접효과** $983 \n- 연차 $\\rightarrow$ 논문 $\\rightarrow$ 연봉: **간접효과** 1.98 x $122 = $241.56\n- 두 효과를 더하면: $983 + $241.56 = $1224.56 = 논문수를 고려하지 않았을 때 연차의 효과\n  - 즉, 연차가 1년 늘때 연봉이 $1224 증가하는 것은 연차 자체의 효과($983)와 논문의 증가에 따른 효과($241)가 합쳐져 나온 결과라고 말할 수 있음.\n- 이 때, 논문의 수가 연차와 연봉의 관계를 (부분) 매개한다고 표현. (mediation)\n\n만약, 연차의 효과 $1224이 논문수를 고려했을 때 줄어든($983) 수준을 훨씬 넘어 통계적으로 유의하지 않을 정도로 0에 가까워진다면, 연차의 효과는 모두 논문의 효과를 거쳐 나타나는 것이라고 말할 수 있음. 이 때, 완전 매개 (fully mediate)한다고 표현함.\n\n![](images/salary_model3.png){width=400}\n\n매개효과의 통계적 분석 절차는 여러 방식이 제시되고 있으나, 일반적인 절차는 부트스랩핑(bootstraping)을 통해 추정하는 것임.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(psych)\nmod_med <- mediate(salary ~ time + (pubs), data = acad0)\n```\n:::\n\n\n![](images/mediation_salary.png){width=500}\n\n\n::: {.cell}\n\n:::\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod_med)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: mediate(y = salary ~ time + (pubs), data = acad0)\n\nDirect effect estimates (traditional regression)    (c') X + M on Y \n            salary      se     t df     Prob\nIntercept 43082.39 3099.49 13.90 12 9.26e-09\ntime        982.87  452.06  2.17 12 5.04e-02\npubs        121.80  149.70  0.81 12 4.32e-01\n\nR = 0.73 R2 = 0.53   F = 6.78 on 2 and 12 DF   p-value:  0.0107 \n\n Total effect estimates (c) (X on Y) \n            salary      se     t df     Prob\nIntercept 43658.59 2978.02 14.66 13 1.83e-09\ntime       1224.39  336.48  3.64 13 3.00e-03\n\n 'a'  effect estimates (X on M) \n          pubs   se    t df    Prob\nIntercept 4.73 5.59 0.85 13 0.41300\ntime      1.98 0.63 3.14 13 0.00783\n\n 'b'  effect estimates (M on Y controlling for X) \n     salary    se    t df  Prob\npubs  121.8 149.7 0.81 12 0.432\n\n 'ab'  effect estimates (through all  mediators)\n     salary   boot     sd   lower  upper\ntime 241.53 228.65 278.32 -313.47 801.27\n```\n:::\n:::\n\n---\n### Causal Relations\n일반적인 인과관계의 형태에 대해서 분류해보면, (p.76)\n\n![](images/causal_rel2.png){width=100%}\n\n흔히 나타나는 partial redundancy인 Model B의 예를 보면,\n\n![](images/causal_rel3.png){width=430}\n\n\n\n",
    "supporting": [
      "regression2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.2/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.10.1/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}